### PR TITLE
PHOENIX-6554 Pherf CLI option long/short option names do not follow conventions

### PR DESCRIPTION
**Pull request by coolankurmahe**
…w conventions}

### CODE REVIEW

**Comment by kiran-maturi** [comment]
@virajjasani @stoty can you please help with the review

**Review by stoty — CHANGES_REQUESTED** [review]
1. Please follow the Phoenix conventions in the naming of the patch (ie. no {} and : in the commit description)
2. schemaFile is only an example. We have a lot of options that have the same problem, thos should also be fixed.

**Comment by coolankurmahe** [comment]
@stoty Can you please review now ?

**Review by stoty — APPROVED** [review]
+1 LGTM

**Review by virajjasani — APPROVED** [review]

**Comment by gjacoby126** [comment]
@coolankurmahe - there are some Pherf tests failing in DataIngestIT and PherfMainIT, could you please take a look?

**Comment by coolankurmahe** [comment]
> @coolankurmahe - there are some Pherf tests failing in DataIngestIT and PherfMainIT, could you please take a look?

@gjacoby126  The tests failing in DataIngestIT and PherfMainIT, failures are un-related to my PR. (I tested it with almost no change PR ).

**Review by gjacoby126 — APPROVED** [review]
+1, thanks @coolankurmahe

**Pull request merged**
