### PR TITLE
PHOENIX-6122: Upgrade jQuery to 3.5.1

### PR DESCRIPTION
**Pull request by tamaashu**
Following HBase we should also upgrade to jQuery 3.5.1 to avoid security vulnerabilities.

Change-Id: Ie278ed3ee14ea9f3f3298a2fed82013cd55eeb38

### CODE REVIEW

**Comment by joshelser** [comment]
Did you try to start up the tracing ui, @tamaashu? Last I tried, I don't think it actually worked. I'd be pleasantly surprised if it started working again.

**Comment by tamaashu** [comment]
> Did you try to start up the tracing ui, @tamaashu? Last I tried, I don't think it actually worked. I'd be pleasantly surprised if it started working again.

Yeah, was a bit challenging but worked for me. Had to fix the tracing webapp to get it tested. :)
Please see https://github.com/apache/phoenix/pull/887

**Comment by joshelser** [comment]
Nice! I missed #887. Let me try it out. No reason to not just assume the jquery is great, but let's see if I can try it out.

**Comment by joshelser** [comment]
Oh, I just noticed this was submitted. Sorry for the delayed response.

Belated +1 :)

**Pull request closed without merging**
