### PR TITLE
PHOENIX-7353 Disable remote procedure delay in TransformToolIT

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by gjacoby126 — APPROVED** [review]
+1, assuming we get a clean test run. I see the previous run failed on a Docker crash, I kicked it off again.

**Comment by stoty** [comment]
The root cause seems to be 
curl: (6) Could not resolve host: github.com

**Comment by stoty** [comment]
Trying to open another PR for the same patch

**Comment by stoty** [comment]
The docker image creation was successful on the identical PR #1929 .
I have no idea why this PR is cursed.

**Pull request closed without merging**
