### PR TITLE
PHOENIX-6966 UngroupedAggregateRegionScanner.insertEmptyKeyValue() wr…

### PR DESCRIPTION
**Pull request by stoty**
…ites wrong qualifier for encoded CQ tables

### CODE REVIEW

**Comment by gjacoby126** [comment]
@stoty  We're sure that GlobalMutableTxIndexIT.testLastDDLTimestampOnAsyncIndexes with columnEncoding=false failing with an NPE is unrelated?

**Comment by stoty** [comment]
Yes I am @gjacoby126 .
I have successfully re-run GlobalMutableTxIndexIT test locally a few times witout problem.

Also, I have checked https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1617/1/artifact/yetus-general-check/output/archiver/phoenix-core/target/failsafe-reports/org.apache.phoenix.end2end.index.GlobalMutableTxIndexIT.txt.gz , and it seems like the minicluster just died /was shutting down when the error happened.

Also, GlobalMutableTxIndexIT doesn't specifically use the changed code:
The added emptyCQ initialization code gets called in most tests for the create table statements, 
but as we're always creating new tables in this test, insertEmptyKeyValue() never gets called.

**Comment by stoty** [comment]
rebased so that CI can run on this again.
The patch is otherwise unchanged.

**Review by richardantal — APPROVED** [review]
LGTM
Locally the test run fine for me.

**Pull request closed without merging**
