### PR TITLE
Upgrade ANTLR version to correct generation error with Java 8

### PR DESCRIPTION
**Pull request by gliptak**

### CODE REVIEW

**Comment by JamesRTaylor** [comment]
Thanks, @gliptak. Patch looks fine, but please amend your commit message by prefixing with PHOENIX-2465 so that it gets tied to the JIRA, like this: "PHOENIX-2465 Upgrade ANTLR version to correct generation error with Java 8"

**Comment by gliptak** [comment]
@JamesRTaylor I updated the commit message

**Comment by gliptak** [comment]
@JamesRTaylor Please review. Thanks

**Comment by JamesRTaylor** [comment]
Weird - this was committed here: https://git-wip-us.apache.org/repos/asf?p=phoenix.git;a=commit;h=21e7c7dd20f19e3f2d30387d472940983bf50d02, but I can't seem to find it here: https://github.com/apache/phoenix/. I'll commit it again.

**Pull request closed without merging**
