### PR TITLE
[PHOENIX-6213] Extend Cell Tags to Delete object to store source of operation.

### PR DESCRIPTION
**Pull request by shahrs87**
Cherry-pick of https://github.com/apache/phoenix/pull/978
Hbase api for adding tags are different in branch-1 otherwise remaining logic is the same.

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  11m  4s |  4.x passed  |
| +1 :green_heart: |  compile  |   0m 56s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   1m 27s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 43s |  4.x passed  |
| +0 :ok: |  spotbugs  |   2m 56s |  phoenix-core in 4.x has 950 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 25s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 58s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 58s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 30s |  phoenix-core: The patch generated 59 new + 2746 unchanged - 12 fixed = 2805 total (was 2758)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 43s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m  5s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 194m 38s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 39s |  The patch does not generate ASF License warnings.  |
|  |   | 228m  4s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.index.DropMetadataIT |
|   | phoenix.end2end.LocalIndexSplitMergeIT |
|   | phoenix.end2end.index.GlobalIndexOptimizationIT |
|   | phoenix.end2end.ReverseScanIT |
|   | phoenix.end2end.index.MutableIndexIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1008/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1008 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux cdc2ff2083ae 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 1261c3f |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1008/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1008/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1008/1/testReport/ |
| Max. process+thread count | 6206 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1008/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by shahrs87** [comment]
Crashing tests ran fine on my machine. 
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.phoenix.tx.ParameterizedTransactionIT
[INFO] Running org.apache.phoenix.end2end.index.GlobalMutableNonTxIndexWithLazyPostBatchWriteIT



  
[INFO] Tests run: 52, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 315.144 s - in org.apache.phoenix.tx.ParameterizedTransactionIT
[INFO] Tests run: 84, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 602.451 s - in org.apache.phoenix.end2end.index.GlobalMutableNonTxIndexWithLazyPostBatchWriteIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 136, Failures: 0, Errors: 0, Skipped: 0
```

**Comment by shahrs87** [comment]
All tests succeeded locally. @gjacoby126 
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running org.apache.phoenix.end2end.LocalIndexSplitMergeIT
[INFO] Running org.apache.phoenix.end2end.index.GlobalIndexOptimizationIT
[INFO] Running org.apache.phoenix.end2end.index.MutableIndexIT
[INFO] Running org.apache.phoenix.end2end.ReverseScanIT
[INFO] Running org.apache.phoenix.end2end.index.DropMetadataIT


[INFO] Tests run: 5, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 90.276 s - in org.apache.phoenix.end2end.ReverseScanIT
[INFO] Tests run: 7, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 129.536 s - in org.apache.phoenix.end2end.index.GlobalIndexOptimizationIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 50.516 s - in org.apache.phoenix.end2end.index.DropMetadataIT
[INFO] Tests run: 3, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 273.915 s - in org.apache.phoenix.end2end.LocalIndexSplitMergeIT
[INFO] Tests run: 153, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,007.908 s - in org.apache.phoenix.end2end.index.MutableIndexIT
[INFO] 
[INFO] Results:
```

**Review by gjacoby126 — APPROVED** [review]
+1, thanks @shahrs87

**Pull request merged**
