### PR TITLE
PHOENIX-2464 Convert phoenix-spark module to 'JUnitSuite' instead of …

### PR DESCRIPTION
**Pull request by gliptak**
…'FunSuite'

### CODE REVIEW

**Comment by jmahonin** [comment]
Hi @gliptak 

I tried to run the tests with the patch applied, and got a number of failures. I think that 'beforeAll' and 'afterAll' aren't actually getting invoked in with the JUnitSuite for some reason.

I tried adding the '@BeforeClass' and '@AfterClass' annotations, but JUnit warns that the methods should be static. Sadly, I think the only way to make that work is with a companion object (e.g. 'object PhoenixSparkIT' which contains the beforeAll and afterAll definitions).

**Comment by gliptak** [comment]
@jmahonin Could you run the tests locally (my local setup is not quite working ...)? Thanks

**Comment by gliptak** [comment]
Now it runs locally.

**Comment by jmahonin** [comment]
Definitely closer, it does run now, but it takes about 4x longer to run than before. The 'doSetup' and 'doTeardown' used to be run only at the very beginning and at the very end, and now they're being run before every test due to the '@Before' and '@After' annotations.

I wonder if it's possible to do something like the 'ScalaClassRuleTest' in [1] and either specify a '@BeforeAll' or an '@ClassRule' in a companion object and move the 'doSetup' and 'doTeardown' there?

[1] http://randomallsorts.blogspot.ca/2012/11/junit-411-whats-new-rules.html

**Comment by gliptak** [comment]
I measured 2x longer (with the Scalatest throwing warnings/errors during tear down ...). I will try to add the companion object.

**Comment by gliptak** [comment]
Scala "static" methods on the companion object are not recognized as such by the ```@BeforeClass``` and ```@AfterClass``` annotations.

**Comment by gliptak** [comment]
Another possibility is to duplicate ```BaseHBaseManagedTimeIT```/```BaseTest``` functionality in ```Scala```/```FunSuite``` ...

**Comment by jmahonin** [comment]
Thanks @gliptak for looking into this.

I'll spend a bit of time seeing if I can work something out here. I think the main goal is just to try be more compatible with JUnit annotations in inherited classes, but I do like having these run as fast as possible as well.

I don't think it's necessarily a major problem if we do nothing here either - the issue only became apparent after merging in transaction support, a pretty large infrastructure addition, which only took a few lines to work around with the existing tests.

**Pull request closed without merging**
