### PR TITLE
PHOENIX-6338 TxCheckpointIT frequently hangs on 4.x

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 33s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 24s |  master passed  |
| +0 |  hbaserecompile  |  22m 49s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 32s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 52s |  master passed  |
| +0 :ok: |  spotbugs  |   3m  9s |  phoenix-core in master has 955 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 15s |  the patch passed  |
| +0 |  hbaserecompile  |  18m 50s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  1s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  1s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 31s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 17s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 103m  2s |  phoenix-core in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 154m 49s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1109/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1109 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 1b92c758409f 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 2c6bd1c |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1109/1/testReport/ |
| Max. process+thread count | 13941 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1109/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
@stoty how come [unit](https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1109/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt) did not show failure? I thought issue while creating shaded jar is still coming up (as per PHOENIX-6308). Yetus run does perform `mvn verify` with `mvn install` phase right?
In fact, I just saw the same issue (last 2 builds) after successful build of `phoenix-core` module on PR#1096.

**Comment by virajjasani** [comment]
+1(non-binding) for the changes btw

**Review by gjacoby126 — APPROVED** [review]
+1

**Comment by stoty** [comment]
> @stoty how come [unit](https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1109/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt) did not show failure? I thought issue while creating shaded jar is still coming up (as per PHOENIX-6308). Yetus run does perform `mvn verify` with `mvn install` phase right?
> In fact, I just saw the same issue (last 2 builds) after successful build of `phoenix-core` module on PR#1096.

It seems that the maven bug is not deterministic. For example I almost always see it in -connectors, but I get full successful runs in core sometimes.

**Pull request closed without merging**
