### PR TITLE
PHOENIX-6228 : Close Admin resources for certain workflows

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Review by gjacoby126 — APPROVED** [review]
Good catches, @virajjasani . (And thank you -- a couple of those you fixed were leaks I apparently wrote...(sigh) ). +1

**Comment by gjacoby126** [comment]
Will merge after we get a test run.

**Comment by virajjasani** [comment]
Thanks you @gjacoby126 for the review. 
Test results for 4.x patch is available on Jira [PHOENIX-6228](https://issues.apache.org/jira/browse/PHOENIX-6228) , whereas test results for master branch might not come until most probably [PHOENIX-6230](https://issues.apache.org/jira/browse/PHOENIX-6230) is fixed because without the fix, github precommit build is timing out apparently: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/view/change-requests/job/PR-976/

I also tried uploading same patch on Jira and awaiting result but I think precommit Jira too will mostly timeout due to PHOENIX-6230. The issue seems with master branch only, 4.x is doing good with `ViewConcurrencyAndFailureIT` test.

**Comment by gjacoby126** [comment]
@virajjasani - makes sense. I'll merge this PR.

**Pull request merged**
