### PR TITLE
PHOENIX-5062 Create a new repo for the phoenix connectors

### PR DESCRIPTION
**Pull request by twdsilva**
@karanmehta93  or @vincentpoon  can you please review? I already moved these modules to the new phoenix-connectors repo.

### CODE REVIEW

**Comment by vincentpoon** [comment]
+1

**Comment by vincentpoon** [comment]
@twdsilva I think phoenix-client and phoenix-assembly have dependencies on these projects, so will have to be adjusted as well?

**Comment by twdsilva** [comment]
@vincentpoon  I forgot to include the pom changes for phoenix-client and phoenix-assembly. Since the phoenix-connectors haven't been released, I removed the dependencies on the connectors.

**Comment by twdsilva** [comment]
I filed https://issues.apache.org/jira/browse/PHOENIX-5202 to create a similar client jar in the connectors repo.

**Comment by twdsilva** [comment]
We

**Pull request closed without merging**
