### PR TITLE
PHOENIX-6114 Create shaded phoenix-pherf and remove lib dir from asse…

### PR DESCRIPTION
**Pull request by stoty**
…mbly

remove pherf-cluster.py
remove phoenix-pherf-minimal shaded jar
remove /lib dir from assembly
remove /dev library from assemby
shade phoenix-pherf instead
move phoenix-pherf.jar to root
update scripts for new jar names and paths

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 17s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 23s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 47s |  4.x passed  |
| +1 :green_heart: |  compile  |   2m  5s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   2m  8s |  4.x passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   7m 34s |  root in the patch failed.  |
| +1 :green_heart: |  compile  |   1m 56s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 56s |  the patch passed  |
| +1 :green_heart: |  pylint  |   0m 10s |  The patch generated 0 new + 87 unchanged - 31 fixed = 87 total (was 118)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  4s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 275m 13s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m 33s |  The patch generated 1 ASF License warnings.  |
|  |   | 311m 30s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.pherf.PherfMainIT |
|   | phoenix.pherf.DataIngestIT |
|   | phoenix.pherf.SchemaReaderIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1132 |
| Optional Tests | dupname asflicense pylint xml javac javadoc unit compile |
| uname | Linux 289ad647350d 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 83f8f73 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/artifact/yetus-general-check/output/whitespace-tabs.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 4831 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf phoenix-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/1/console |
| versions | git=2.7.4 maven=3.3.9 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 22s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 18s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m 57s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 41s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   1m 40s |  4.x passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 13s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   6m 29s |  root in the patch failed.  |
| +1 :green_heart: |  compile  |   1m 41s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 41s |  the patch passed  |
| +1 :green_heart: |  pylint  |   0m  7s |  The patch generated 0 new + 87 unchanged - 31 fixed = 87 total (was 118)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 41s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 198m 46s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m 44s |  The patch generated 1 ASF License warnings.  |
|  |   | 234m 40s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.index.MutableIndexFailureIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1132 |
| Optional Tests | dupname asflicense pylint xml javac javadoc unit compile |
| uname | Linux 0cb853b851fe 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 83f8f73 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/artifact/yetus-general-check/output/whitespace-tabs.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 4778 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf phoenix-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/2/console |
| versions | git=2.7.4 maven=3.3.9 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by joshelser — APPROVED** [review]
http://phoenix.apache.org/pherf.html needs to be updated after this.

So, quickly moving towards all phoenix artifacts being shaded (self-contained)? I like it!

**Comment by yanxinyi** [comment]
+1 LGTM

Tested locally by running mvn install and checked a few dir.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 15s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  3s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 14s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 40s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   1m 51s |  4.x passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   6m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  pylint  |   0m  6s |  The patch generated 0 new + 87 unchanged - 31 fixed = 87 total (was 118)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m  5s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 41s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 213m 27s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   0m 25s |  The patch generated 1 ASF License warnings.  |
|  |   | 246m 25s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1132 |
| Optional Tests | dupname asflicense pylint xml javac javadoc unit compile |
| uname | Linux af78f069bff6 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 83f8f73 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/artifact/yetus-general-check/output/whitespace-tabs.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 4861 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf phoenix-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1132/3/console |
| versions | git=2.7.4 maven=3.3.9 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by yanxinyi — APPROVED** [review]

**Pull request closed without merging**
