### PR TITLE
PHOENIX-5833 Fix Incorrect results with RVCs and AND operator

### PR DESCRIPTION
**Pull request by dbwong**
https://issues.apache.org/jira/browse/PHOENIX-5833

### CODE REVIEW

**Comment by dbwong** [comment]
@ChinmaySKulkarni or @yanxinyi can you review?

**Comment by dbwong** [comment]
Trying this again, this is critical imo for at least 4.16 since we missed 4.15.... We had discussed this offline and had verbal agreement on the approach months ago. @ChinmaySKulkarni or @yanxinyi can you review?

**Review by ChinmaySKulkarni — APPROVED** [review]

**Comment by ChinmaySKulkarni** [comment]
FYI @yanxinyi please take look at this too. Seems important for 4.16 as Daniel mentioned.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m  0s |  Docker mode activated.  |
| -1 :x: |  patch  |   0m  4s |  https://github.com/apache/phoenix/pull/767 does not apply to 4.x. Rebase required? Wrong Branch? See https://yetus.apache.org/documentation/in-progress/precommit-patchnames for help.  |


| Subsystem | Report/Notes |
|----------:|:-------------|
| GITHUB PR | https://github.com/apache/phoenix/pull/767 |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-767/1/console |
| versions | git=2.17.1 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
The rebased PR for master is #1653

**Pull request closed without merging**
