### PR TITLE
PHOENIX-7173 Update default HBase versions to 2.4.17 and 2.5.7 respec…

### PR DESCRIPTION
**Pull request by stoty**
…tively

### CODE REVIEW

**Comment by virajjasani** [comment]
I wonder if this should be part of IT test so that it won't block all ITs from running https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1785/2/testReport/junit/org.apache.phoenix.hbase.index.write.recovery/TestPerRegionIndexWriteCache/testMultipleRegions/

**Comment by virajjasani** [comment]
Otherwise if tests have already been verified locally, +1

**Comment by stoty** [comment]
The problem is that I added an optimization to the Yetus personality to only rebuild HBase once at the start, and Yetus won't rebuild the new HBase version when we change the HBase version.

This wouldn't be very hard to fix, I just haven't gotten around to doing it.
https://issues.apache.org/jira/browse/PHOENIX-6593

**Comment by stoty** [comment]
At least I assume that that is the problem, as the TestPerRegionIndexWriteCache doesn't fail for me locally, and I don't recall seeing it fail before.

**Comment by virajjasani** [comment]
> and I don't recall seeing it fail before.

yes, me neither.

**Review by virajjasani — APPROVED** [review]

**Comment by stoty** [comment]
I've run the full test suite successfully locally both for 2.4 and 2.5.

**Comment by stoty** [comment]
merged manually

**Pull request closed without merging**
