### PR TITLE
PHOENIX-6950 PhoenixDriver APIs should unlock closeLock only if thread is able to take lock

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Review by shahrs87 — APPROVED** [review]
+1 ltgm.

**Comment by virajjasani** [comment]
Thank you @shahrs87, the checkstyle warnings don't seem relevant, let me merge this soon.

**Comment by shahrs87** [comment]
> let me merge this soon.

@virajjasani  My vote is non-binding. Good to get a review from committer also. FYI.

**Comment by virajjasani** [comment]
oh, my bad

**Review by gjacoby126 — APPROVED** [review]
+1

**Pull request merged**
