### PR TITLE
PHOENIX-7367 - Snapshot based mapreduce jobs fails after HBASE-28401

### PR DESCRIPTION
**Pull request by ujjawal4046**
Jira: PHOENIX-7367

1. Disable mslab for region created within snapshot (by setting hbase.hregion.memstore.mslab.enabled set to false)
2. In TableSnapshotResultIterator - Remove the the SnapshotScanner's close (via ScanningResultIterator) called within next method. It would anyways be closed by the mapper at the end while closing the record reader

### CODE REVIEW

**Review by mnpoonia — APPROVED** [review]

**Comment by virajjasani** [comment]
Previous build has expired, triggered new build: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1941/

**Review by virajjasani — DISMISSED** [review]

**Comment by virajjasani** [comment]
@ujjawal4046 several test failures on the latest build seem relevant? https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1941/3/testReport/

**Comment by virajjasani** [comment]
e.g.
```
java.lang.Exception: java.lang.NullPointerException
	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492) ~[hadoop-mapreduce-client-common-3.2.4.jar:?]
	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552) ~[hadoop-mapreduce-client-common-3.2.4.jar:?]
Caused by: java.lang.NullPointerException
	at org.apache.phoenix.iterate.SnapshotScanner.next(SnapshotScanner.java:163) ~[phoenix-core-server-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.phoenix.iterate.ScanningResultIterator.next(ScanningResultIterator.java:204) ~[phoenix-core-client-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.phoenix.iterate.TableSnapshotResultIterator.next(TableSnapshotResultIterator.java:179) ~[phoenix-core-server-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.phoenix.iterate.LookAheadResultIterator$1.advance(LookAheadResultIterator.java:55) ~[phoenix-core-client-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.phoenix.iterate.LookAheadResultIterator.next(LookAheadResultIterator.java:75) ~[phoenix-core-client-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.phoenix.jdbc.PhoenixResultSet.next(PhoenixResultSet.java:884) ~[phoenix-core-client-5.3.0-SNAPSHOT.jar:?]
	at org.apache.phoenix.mapreduce.PhoenixRecordReader.nextKeyValue(PhoenixRecordReader.java:185) ~[phoenix-core-server-5.3.0-SNAPSHOT.jar:5.3.0-SNAPSHOT]
	at org.apache.hadoop.mapred.MapTask$NewTrackingRecordReader.nextKeyValue(MapTask.java:569) ~[hadoop-mapreduce-client-core-3.2.4.jar:?]
	at org.apache.hadoop.mapreduce.task.MapContextImpl.nextKeyValue(MapContextImpl.java:80) ~[hadoop-mapreduce-client-core-3.2.4.jar:?]
	at org.apache.hadoop.mapreduce.lib.map.WrappedMapper$Context.nextKeyValue(WrappedMapper.java:91) ~[hadoop-mapreduce-client-core-3.2.4.jar:?]
	at org.apache.hadoop.mapreduce.Mapper.run(Mapper.java:145) ~[hadoop-mapreduce-client-core-3.2.4.jar:?]
...
...
```

**Comment by ujjawal4046** [comment]
@virajjasani I have reverted the change for TableSnapshotResultIterator which was causing the test failure due to same optimization of closing early being applied by ScanningResultIterator (which is used outside of MR based snapshot jobs) as well. Fixing it across both iterators isn't feasible without more extensive refactor so parking that. 

Disabling mslab should be sufficient to fix the snapshot issue.

**Review by virajjasani — APPROVED** [review]

**Pull request merged**
