### PR TITLE
PHOENIX-6314 : Utility to identify git commit / Jira fixVersion discrepancies for RC preparation

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  1s |  The patch does not contain any @author tags.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 25s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  7s |  Maven dependency ordering for patch  |
| -1 :x: |  markdownlint  |   0m  1s |  The patch generated 33 new + 0 unchanged - 0 fixed = 33 total (was 0)  |
| -1 :x: |  pylint  |   0m  3s |  The patch generated 9 new + 0 unchanged - 0 fixed = 9 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 1 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 11 line(s) with tabs.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   5m 42s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1090 |
| Optional Tests | dupname asflicense pylint markdownlint |
| uname | Linux 987b4410fb22 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / b4bb3a2 |
| markdownlint | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/artifact/yetus-general-check/output/diff-patch-markdownlint.txt |
| pylint | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/artifact/yetus-general-check/output/diff-patch-pylint.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/artifact/yetus-general-check/output/whitespace-eol.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/artifact/yetus-general-check/output/whitespace-tabs.txt |
| Max. process+thread count | 52 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/1/console |
| versions | git=2.7.4 maven=3.3.9 markdownlint=0.22.0 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 38s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 24s |  Maven dependency ordering for branch  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m  8s |  Maven dependency ordering for patch  |
| -1 :x: |  markdownlint  |   0m  1s |  The patch generated 32 new + 0 unchanged - 0 fixed = 32 total (was 0)  |
| -1 :x: |  pylint  |   0m  2s |  The patch generated 9 new + 0 unchanged - 0 fixed = 9 total (was 0)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 11 line(s) with tabs.  |
||| _ Other Tests _ |
| +0 :ok: |  asflicense  |   0m  0s |  ASF License check generated no output?  |
|  |   |   5m 40s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1090 |
| Optional Tests | dupname asflicense pylint markdownlint |
| uname | Linux 432cf98d6c83 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / b4bb3a2 |
| markdownlint | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/2/artifact/yetus-general-check/output/diff-patch-markdownlint.txt |
| pylint | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/2/artifact/yetus-general-check/output/diff-patch-pylint.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/2/artifact/yetus-general-check/output/whitespace-tabs.txt |
| Max. process+thread count | 52 (vs. ulimit of 30000) |
| modules | C:  U:  |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1090/2/console |
| versions | git=2.7.4 maven=3.3.9 markdownlint=0.22.0 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
I don't think we need to duplicate this in 4.x, having the release tools in master is enough.

**Comment by virajjasani** [comment]
Oh yes definitely, it's just a utility, not a bug fix or feature. Closing the PR.

**Pull request closed without merging**
