### PR TITLE
PHOENIX-6985 Setting server-side masking flag default to false

### PR DESCRIPTION
**Pull request by lokiore**

### CODE REVIEW

**Comment by stoty** [comment]
Please make sure that the commit message has the JIRA id in the proper format.

**Comment by jpisaac** [comment]
@lokiore The following JIRA title may be more appropriate or something along these -

"Setting server-side masking config default to false"

**Comment by lokiore** [comment]
@jpisaac I see 2 test failures, one is passing locally and Failover one is failing even without the commit. Can you please take a look. I'll push an empty commit to rerun the tests.

**Comment by jpisaac** [comment]
@lokiore I understand they are flappers after talking to @virajjasani @tkhurana, Is there a way to mark them as such?

**Review by jpisaac — APPROVED** [review]
LGTM +1

**Comment by lokiore** [comment]
> @lokiore I understand they are flappers after talking to @virajjasani @tkhurana, Is there a way to mark them as such?

I am not sure if we can do something here other than Ignore which I assume we don't want. maybe some plugin can be added at jenkins like Result Test Analyser or do we already have that @virajjasani !?

**Review by gjacoby126 — APPROVED** [review]
+1

**Review by virajjasani — APPROVED** [review]

**Comment by virajjasani** [comment]
@jpisaac we want this in 5.1 too?

**Comment by lokiore** [comment]
@virajjasani create PR for 5.1 to let tests run :- https://github.com/apache/phoenix/pull/1634

**Pull request merged**
