### PR TITLE
PHOENIX-7138 Import netty-bom to make sure all netty 4.1 modules shar…

### PR DESCRIPTION
**Pull request by stoty**
…e the same version

### CODE REVIEW

**Comment by stoty** [comment]
I've re-run the failing tests successfully locally.

**Review by richardantal — APPROVED** [review]
LGTM
I checked the dependency tree, all netty 4.1 version are 4.1.104.Final
However we have netty jar 3.10.6 coming from com.google.inject.extensions:guice-servlet, but that should be OK

**Comment by stoty** [comment]
Yes, Netty 3 and 4 can coexist, so that's fine (We could probably exclude netty3, but that's a different hill to climb)

**Comment by stoty** [comment]
merged manually

**Pull request closed without merging**
