### PR TITLE
PHOENIX-6199 Generate different query plan depending upon if the source is index table or data table

### PR DESCRIPTION
**Pull request by tkhurana**
https://github.com/apache/phoenix/pull/937/files#diff-71a73ee7d5c142ff10aac951e6237d22d7316681ca3818c06248b03907082077

IT Test for the diff above. Please refer to the code change above

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  10m 46s |  4.x passed  |
| +1 :green_heart: |  compile  |   0m 55s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 53s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 45s |  4.x passed  |
| +0 :ok: |  spotbugs  |   2m 54s |  phoenix-core in 4.x has 946 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 15s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 54s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 54s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 56s |  phoenix-core: The patch generated 53 new + 962 unchanged - 16 fixed = 1015 total (was 978)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 41s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m  1s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 126m 53s |  phoenix-core in the patch failed.  |
| -1 :x: |  asflicense  |   0m 37s |  The patch generated 1 ASF License warnings.  |
|  |   | 157m 46s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.DerivedTableIT |
|   | phoenix.end2end.BackwardCompatibilityForSplitableSyscatIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/958 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 0fbd2d7aaa57 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / f0f2f74 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 7152 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 35s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x-PHOENIX-5182 Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  10m 55s |  4.x-PHOENIX-5182 passed  |
| +1 :green_heart: |  compile  |   0m 55s |  4.x-PHOENIX-5182 passed  |
| +1 :green_heart: |  checkstyle  |   0m 31s |  4.x-PHOENIX-5182 passed  |
| +1 :green_heart: |  javadoc  |   0m 45s |  4.x-PHOENIX-5182 passed  |
| +0 :ok: |  spotbugs  |   2m 53s |  phoenix-core in 4.x-PHOENIX-5182 has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 12s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 32s |  phoenix-core: The patch generated 0 new + 62 unchanged - 3 fixed = 62 total (was 65)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 44s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m  5s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 128m 12s |  phoenix-core in the patch failed.  |
| -1 :x: |  asflicense  |   0m 38s |  The patch generated 1 ASF License warnings.  |
|  |   | 158m 35s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.StoreNullsIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/958 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 0d8b501c6702 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x-PHOENIX-5182 / 0d33ce9 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/2/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 7005 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-958/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by tkhurana** [comment]
@gokceni @kadirozde @swaroopak

**Review by swaroopak — APPROVED** [review]
+1, thanks!

**Pull request merged**
