### PR TITLE
PHOENIX-6241 ViewIndexId sequences collide with ones created on the p…

### PR DESCRIPTION
**Pull request by yanxinyi**
…re-4.15 version

### CODE REVIEW

**Comment by yanxinyi** [comment]
During the upgrade, we disallow certain operations, which results in the query that returns an empty ResultSet from the sequence table(sequence table is not empty). I'm sure that scn and atomic flag upgradeRequired make things diff than the regular query connection. For this reason, I moved  merge view index id logic at the end of the upgradeSystemTables method. In addition, I also added a MergeViewIndexIdSequencesTool that can run it separately to catch up merge view index id logic later.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  11m 57s |  4.x passed  |
| +1 :green_heart: |  compile  |   0m 59s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   1m  6s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 48s |  4.x passed  |
| +0 :ok: |  spotbugs  |   3m 14s |  phoenix-core in 4.x has 950 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m 32s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 59s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 59s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m  6s |  phoenix-core: The patch generated 33 new + 2163 unchanged - 4 fixed = 2196 total (was 2167)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 47s |  the patch passed  |
| -1 :x: |  spotbugs  |   3m 24s |  phoenix-core generated 1 new + 950 unchanged - 0 fixed = 951 total (was 950)  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 191m 49s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 33s |  The patch does not generate ASF License warnings.  |
|  |   | 232m 10s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:phoenix-core |
|  |  Possible null pointer dereference of cmdLine in org.apache.phoenix.util.MergeViewIndexIdSequencesTool.parseOptions(String[]) on exception path  Dereferenced at MergeViewIndexIdSequencesTool.java:cmdLine in org.apache.phoenix.util.MergeViewIndexIdSequencesTool.parseOptions(String[]) on exception path  Dereferenced at MergeViewIndexIdSequencesTool.java:[line 66] |
| Failed junit tests | phoenix.end2end.ViewTTLIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1004 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux afbc0f0ba496 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 4f8eab9 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/artifact/yetus-general-check/output/new-spotbugs-phoenix-core.html |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/testReport/ |
| Max. process+thread count | 6212 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1004/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by yanxinyi** [comment]
@ChinmaySKulkarni @gjacoby126 can you take a look, thanks!

**Review by gjacoby126 — APPROVED** [review]
+1, thanks for catching this bug in my 4.15 fix.

**Review by ChinmaySKulkarni — APPROVED** [review]
+1

**Pull request closed without merging**
