### PR TITLE
PHOENIX-5894 Table versus Table Full Outer join on Salted tables not …

### PR DESCRIPTION
**Pull request by chrajeshbabu**
…working

### CODE REVIEW

**Comment by chrajeshbabu** [comment]
The test case failure because the salt column getting added twice. Looking into it.

**Comment by chrajeshbabu** [comment]
The test case failure is not related to the fix.
@stoty @SergeySoldatov  could you please take a look at it.

**Review by ss77892 — APPROVED** [review]
LGTM.

**Comment by chrajeshbabu** [comment]
Thanks @SergeySoldatov  for the reviews.

**Pull request merged**
