### PR TITLE
PHOENIX-7359 BackwardCompatibilityIT throws NPE with Hbase 2.6 profile

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by virajjasani — APPROVED** [review]
+1 for the change, though i think `5.1.3` might work for `2.6` profile also

**Comment by stoty** [comment]
No, we have never backported 2.6 support to 5.1, much less into 5.1.3.

I think that backporting 2.6 support to 5.1 would be a goodea BTW.

**Comment by virajjasani** [comment]
Ah right, my bad

**Comment by stoty** [comment]
merged manually.

**Pull request closed without merging**
