### PR TITLE
Revert "PHOENIX-6751 Force using range scan vs skip scan when using large IN clause"

### PR DESCRIPTION
**Pull request by jpisaac**
This reverts commit 04e79487d44c77a5ba9da6918f189c2bab94a2b8.

### CODE REVIEW

**Comment by jpisaac** [comment]
@tkhurana

**Comment by gjacoby126** [comment]
@jpisaac - could you please explain the reason for the revert? You mentioned to me offline that there's a new version of the patch coming with improvements?

How does the revert compare to doing either an addendum or a new JIRA on top of 6751?

**Comment by jpisaac** [comment]
@gjacoby126 closing this one, As the commit was signed with my SFDC id.

This patch is not in 5.1 branch, so will need to make another for that branch, It just seems too confusing, master branch having the patch  + addendum and 5.1 branch being just one patch.

Also realized the PR is missing the test annotation here 

https://github.com/apache/phoenix/pull/1492/files#diff-e26d2c0bba67152839292ee676236eacf2d8d7cc42e9f3b4e5325f50c0a32e2bL1892

**Review by tkhurana — APPROVED** [review]

**Review by gjacoby126 — APPROVED** [review]
+1

**Pull request merged**
