### PR TITLE
PHOENIX-6120 Change IndexMaintainer for SINGLE_CELL_ARRAY_WITH_OFFSET indexes

### PR DESCRIPTION
**Pull request by gokceni**

### CODE REVIEW

**Comment by gokceni** [comment]
@kadirozde @swaroopak @ChinmaySKulkarni @gjacoby126 @tkhurana

**Review by swaroopak — APPROVED** [review]
LGTM

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 26s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x-PHOENIX-5923 Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 23s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 43s |  4.x-PHOENIX-5923 passed  |
| +1 :green_heart: |  compile  |   1m 29s |  4.x-PHOENIX-5923 passed  |
| +1 :green_heart: |  checkstyle  |   2m  0s |  4.x-PHOENIX-5923 passed  |
| +1 :green_heart: |  javadoc  |   1m 54s |  4.x-PHOENIX-5923 passed  |
| +0 :ok: |  spotbugs  |   4m 25s |  root in 4.x-PHOENIX-5923 has 1000 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   2m 54s |  phoenix-core in 4.x-PHOENIX-5923 has 946 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 10s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   6m  5s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 29s |  the patch passed  |
| +1 :green_heart: |  cc  |   1m 29s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 29s |  the patch passed  |
| -1 :x: |  checkstyle  |   2m  1s |  root: The patch generated 140 new + 5206 unchanged - 37 fixed = 5346 total (was 5243)  |
| +1 :green_heart: |  prototool  |   0m  1s |  There were no new prototool issues.  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 51s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   7m 42s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 183m 35s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m  5s |  The patch generated 1 ASF License warnings.  |
|  |   | 238m 16s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.IndexToolForNonTxGlobalIndexIT |
|   | phoenix.tx.TransactionIT |
|   | phoenix.end2end.SystemCatalogRollbackEnabledIT |
|   | phoenix.end2end.UpsertSelectIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/986 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile cc prototool |
| uname | Linux 1bd7751993ab 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x-PHOENIX-5923 / 9f5a0bf |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 5868 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-986/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 prototool=1.10.0-dev |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by kadirozde — APPROVED** [review]
+1, Thanks

**Pull request closed without merging**
