### PR TITLE
PHOENIX-7141 Use relocate by default for phoenix-server shading

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
This depends on PHOENIX-7139, so marking this as draft until that one is merged.

**Comment by virajjasani** [comment]
Overall good, just awaiting new build results: 
https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1783/5/

**Comment by stoty** [comment]
The tests have passed with the latest rebase.
Can you take another look @virajjasani  ?

**Comment by stoty** [comment]
Can you take another look @virajjasani ?
This has had a few successful builds 
(BTW unfortunately we don't test the shaded JARs at all, the test suite wouldn't detect if all shaded JARS were empty)

**Review by virajjasani — APPROVED** [review]

**Pull request closed without merging**
