### PR TITLE
PHOENIX-6329 Eliminate or serialize minicluster restart operations in…

### PR DESCRIPTION
**Pull request by stoty**
… Integration tests

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   6m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 59s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 26s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 46s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   2m  9s |  4.x passed  |
| +0 :ok: |  spotbugs  |   4m 54s |  root in 4.x has 999 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   3m  5s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   1m 13s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 10s |  root in the patch failed.  |
| -1 :x: |  javac  |   1m 10s |  root in the patch failed.  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  5s |  the patch passed  |
| -1 :x: |  spotbugs  |   1m  3s |  phoenix-core in the patch failed.  |
| -1 :x: |  spotbugs  |   1m 30s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   1m  9s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 18s |  The patch does not generate ASF License warnings.  |
|  |   |  45m 50s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1101 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile xml |
| uname | Linux 970e0d57ae6d 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 6fe6052 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-spotbugs-phoenix-core.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-spotbugs-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/testReport/ |
| Max. process+thread count | 84 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 46s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  5s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 13s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 40s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   2m  0s |  4.x passed  |
| +0 :ok: |  spotbugs  |   4m 36s |  root in 4.x has 999 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   3m  2s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 18s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   6m 55s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 40s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 34s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  2s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   8m 14s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 200m 33s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 20s |  The patch does not generate ASF License warnings.  |
|  |   | 255m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/4/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1101 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile xml |
| uname | Linux 8a7e5bd2dfb9 4.15.0-101-generic #102-Ubuntu SMP Mon May 11 10:07:26 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 4b4a366 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/4/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/4/testReport/ |
| Max. process+thread count | 4865 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/4/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by gjacoby126 — APPROVED** [review]
+1, assuming that usage data shows this makes the tests more stable. Thanks @stoty

**Comment by virajjasani** [comment]
With this, we have perf advantage over #1080 but still full build took 4h16m. I believe a couple more build runs could provide better results.

**Comment by stoty** [comment]
Comparing the ASF jenkins runtimes is not trivial. We've got both 16 and 24 core machines in the pool, and there may or may not be another task running in parallel.
On my SSD desktop the difference to master was within the margin of error, but I do not have access to proper spinning rust hard disk machines or dedicated VMs to do an apples to apples comparison with HDD I/O.

**Comment by stoty** [comment]
The last build had a successful test run (the maven shading bug caused a build failure, but that's a different issue)
and the maven test part took 2:02 .
I think that's good enough performance wise, and if we still see a performance regression, we can always work on improving it.

**Comment by virajjasani** [comment]
Got it, Thanks. I think it makes sense, anyways when I tried in my VM with and without #1080 , the difference was apparent. Anyways, synchronizing the key functionality of starting and shuting down miniCluster is necessary. Agree with moving forward with this patch.

> and the maven test part took 2:02

Great.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m  0s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  12m  1s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 41s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 33s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   2m  5s |  4.x passed  |
| +0 :ok: |  spotbugs  |   4m 44s |  root in 4.x has 999 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   3m 14s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   7m 10s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 46s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 36s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  3s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 15s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   8m 40s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 216m 52s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 20s |  The patch does not generate ASF License warnings.  |
|  |   | 269m 45s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/6/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1101 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile xml |
| uname | Linux 02217a66740e 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 49994f8 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/6/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/6/testReport/ |
| Max. process+thread count | 4773 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1101/6/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
