### PR TITLE
PHOENIX-6078 Remove Internal Phoenix Connections from parent LinkedQueue when closed

### PR DESCRIPTION
**Pull request by sakshamgangwar**
https://issues.apache.org/jira/browse/PHOENIX-6078

### CODE REVIEW

**Comment by dbwong** [comment]
Please open up follow up jira for unhappy path handling.  Thanks.

**Comment by sakshamgangwar** [comment]
> Please open up follow up jira for unhappy path handling. Thanks.

@dbwong added that here: https://issues.apache.org/jira/browse/PHOENIX-6079

**Comment by gjacoby126** [comment]
@ChinmaySKulkarni and @sakshamgangwar , what's the status of this PR? I see that it's approved (and skimming through seems pretty straightforward). Any reason it hasn't been committed?

**Review by gjacoby126 — APPROVED** [review]
+1

**Comment by gjacoby126** [comment]
Kicked off a Yetus build to make sure this still passes tests. If it's green I'll merge this tomorrow.

**Comment by sakshamgangwar** [comment]
@gjacoby126 Thanks for triggering the tests again.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 45s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  13m  0s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m 20s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 48s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 58s |  4.x passed  |
| +0 :ok: |  spotbugs  |   4m  3s |  phoenix-core in 4.x has 950 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   7m 18s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  5s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  5s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 46s |  phoenix-core: The patch generated 6 new + 464 unchanged - 0 fixed = 470 total (was 464)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m 29s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 140m 56s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 47s |  The patch does not generate ASF License warnings.  |
|  |   | 180m 51s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-858/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/858 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux a14d3d98499f 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 55c41f7 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-858/2/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-858/2/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-858/2/testReport/ |
| Max. process+thread count | 6519 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-858/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by gjacoby126** [comment]
Test passed save for one JVM crash. Merging.

**Pull request merged**
