### PR TITLE
PHOENIX-1733: sqlline.py doesn't allow connecting with a tenant-specific...

### PR DESCRIPTION
**Pull request by abisek**

### CODE REVIEW

**Comment by gabrielreid** [comment]
Looks good, except that this breaks sqlline.py for Windows. Could you take a look at how psql.py uses the same approach but also uses subprocess.list2cmdline to allow running it on Windows, and try to use the same approach here?

**Comment by abisek** [comment]
@gabrielreid - good catch! I updated the code to handle the shell quoting in a platform-specific manner. 

I verified the changes on Unix. I'm going to try it on Windows by end of the day today.

**Comment by abisek** [comment]
Verified on Windows as well:
```
C:\Phoenix\phoenix\bin>python sqlline.py asreeniva-wsl2.internal.salesforce.com:2181:/hbase;TenantId=t1
Setting property: [isolation, TRANSACTION_READ_COMMITTED]
issuing: !connect jdbc:phoenix:asreeniva-wsl2.internal.salesforce.com:2181:/hbase;TenantId=t1 none none org.apache.phoenix.jdbc.PhoenixDriver
Connecting to jdbc:phoenix:asreeniva-wsl2.internal.salesforce.com:2181:/hbase;TenantId=t1
...
```

**Comment by gabrielreid** [comment]
This has been pushed to master and 4.x branch. Thanks @abisek! 

@JamesRTaylor can you close this PR, or give me the required rights to do so?

**Pull request closed without merging**
