### PR TITLE
PHOENIX-6600 Replace deprecated getCall with updated getRpcCall

### PR DESCRIPTION
**Pull request by kiran-maturi**

### CODE REVIEW

**Comment by gjacoby126** [comment]
@ArkenKiran - Looks like there are test failures (an NPE) with PhoenixIndexRpcSchedulerTest. Could you please take a look?

**Comment by kiran-maturi** [comment]
@gjacoby126 Thanks for looking into it. I have fixed the test cases

**Comment by virajjasani** [comment]
Test results for 2nd build: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1356/2/testReport/

Btw this PR and Jira title can be changed to "Replace deprecated getCall with updated getRpcCall" because method not found seems un-relevant.
And I will trigger one more build to ensure the recent failed tests are not repetitive (although they are known flakies).

**Comment by kiran-maturi** [comment]
@virajjasani thanks for reviewing. The test are flaky in my local as well sometimes they fail and sometimes they pass

**Comment by virajjasani** [comment]
The latest build looks good

**Review by virajjasani — APPROVED** [review]
+1

**Comment by virajjasani** [comment]
@kiran-maturi could you also create another PR against 5.1 branch? That way we will have all tests run in 5.1 as well, and once done, both PRs can be merged together.

**Pull request merged**
