### PR TITLE
PHOENIX-7391 do not return tenant_id column when getting columns list using PhoenixRuntime.generateColumnInfo

### PR DESCRIPTION
**Pull request by rejeb**

### CODE REVIEW

**Comment by stoty** [comment]
restarted CI.

**Comment by stoty** [comment]
Please fix the checkstyle error, @rejeb

**Comment by rejeb** [comment]
Done, I also renamed jira and commit message to match the PR title.

**Comment by stoty** [comment]
The checkstyle warining is not related to this patch.

**Comment by stoty** [comment]
merged manually.

**Comment by stoty** [comment]
I had to add the JIRA id to the commit message.

**Pull request closed without merging**
