### PR TITLE
PHOENIX-6250 Fix ViewMetadataIT test flapper (addendum)

### PR DESCRIPTION
**Pull request by yanxinyi**

### CODE REVIEW

**Comment by virajjasani** [comment]
@yanxinyi View's not getting deleted while parent was dropped has something to do with SYSTEM.TASK? Do we save some intermittent state while dropping view in SYSTEM.TASK?

**Comment by yanxinyi** [comment]
> @yanxinyi View's not getting deleted while parent was dropped has something to do with SYSTEM.TASK? Do we save some intermittent state while dropping view in SYSTEM.TASK?

Yes. The test issued a cascade drop and then force SYSTEM.TASK to run; however, it might be the race condition that SYSTEM.TASK already started and caused race condition. Changing the running interval config to the max value can avoid this behavior.

**Comment by ChinmaySKulkarni** [comment]
> @yanxinyi View's not getting deleted while parent was dropped has something to do with SYSTEM.TASK? Do we save some intermittent state while dropping view in SYSTEM.TASK?

Yes we use the SYSTEM.TASK table for dropping child views asynchronously whenever a drop <parent table/view> cascade command is issued. By setting these configs, we are ensuring that the background TaskRegionObserver thread does not automatically pick up DropChildViewTasks. This prevents race conditions in the test and makes it more deterministic since we already explicitly call runDropChildViewsTask() in the test case wherever cascade drops are issued:
https://github.com/apache/phoenix/blob/ba6ad70541d9dae88ab574df3889f5fe2c0ef7fa/phoenix-core/src/it/java/org/apache/phoenix/end2end/ViewMetadataIT.java#L720-L726

**Review by ChinmaySKulkarni — APPROVED** [review]
+1. Not sure why the hadoop qa didn't run on this. @yanxinyi any issues with it?

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 24s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  14m 24s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m  2s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 26s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 46s |  4.x passed  |
| +0 :ok: |  spotbugs  |   3m  0s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m  3s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  0s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  0s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 25s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 46s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 13s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 199m  0s |  phoenix-core in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 11s |  The patch does not generate ASF License warnings.  |
|  |   | 235m 34s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1105/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1105 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 981d8332b4a6 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / a175cc0 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1105/2/testReport/ |
| Max. process+thread count | 5763 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1105/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
