### PR TITLE
PHOENIX-7041 Populate ROW_KEY_PREFIX column when creating views

### PR DESCRIPTION
**Pull request by jpisaac**
Some of the tests are still failing. Will need additional fixes (separate JIRAS)

### CODE REVIEW

**Comment by jpisaac** [comment]
@kadirozde @lokiore @tkhurana

**Review by kadirozde — APPROVED** [review]
LGTM. Thanks

**Comment by jpisaac** [comment]
@kadirozde @virajjasani @lokiore Updated the PR with refactored tests. This is the version I would like to checkin. Please review when you get the chance. Thanks

**Review by lokiore — APPROVED** [review]
LGTM, Thanks a lot!

**Pull request merged**
