### PR TITLE
PHOENIX-4909 Missing the phoenix-loadbalancer module dependency

### PR DESCRIPTION
**Pull request by MrSandmanRUS**
Missing the phoenix-loadbalancer module dependency in phoenix-assembly/pom.xml.

Fixed phoenix-assembly.pom
Fixed phoenix_utils.py

### CODE REVIEW

**Comment by MrSandmanRUS** [comment]
@joshelser you welcome =)

**Comment by MrSandmanRUS** [comment]
@joshelser these are the fixes that we discussed in PHOENIX-4892, can you review please?

**Comment by joshelser** [comment]
Thanks, @MrSandmanRUS. Sorry for the delay, Vitaliy :)

Let me try to merge this today.

**Comment by joshelser** [comment]
Looks like your change doesn't actually get the phoenix-load-balancer jar showing up. Let me modify..

**Comment by MrSandmanRUS** [comment]
ok

**Comment by MrSandmanRUS** [comment]
Oh, ok, I understood, add commit for all-common-jars.xml?

**Comment by MrSandmanRUS** [comment]
Um, there might be a problem, because we can not add something like "phoenix-load-balancer-*.jar" (we also have phoenix-load-balancer-*-tests.jar), in Python I used "phoenix-load-balancer-*[!t][!e][!s][!t][!s].jar", but don't know, can we use this construction in maven.

**Comment by joshelser** [comment]
> we can not add something like "phoenix-load-balancer-*.jar" (we also have phoenix-load-balancer-*-tests.jar)

We have the tests jars included in `lib` for every other Maven module, so I think this is OK.

**Comment by MrSandmanRUS** [comment]
Ok, super, so I can add commit with phoenix-load-balancer-\*.jar

**Pull request closed without merging**
