### PR TITLE
PHOENIX-6961 Using a covered field in hinted non-covered indexed quer…

### PR DESCRIPTION
**Pull request by stoty**
…y fails

### CODE REVIEW

**Comment by kadirozde** [comment]
@stoty, Thank you for fixing this issue! The PR looks good to me. I wonder if we should rename IndexDataColumnRef to UncoveredDataColumnRef or even IndexUncoveredDataColumnRef to make the code more readable. I will approve this PR when you fix the conflicts and get a full pre checking test run.

**Comment by stoty** [comment]
Thanks for the review, @kadirozde.

This PR is just for checking the backport to 5.1

The main PR for master is #1639, which I have already rebased, and has a mostly clean CI run (apart from a known flakey.)
Please review that one.

**Comment by stoty** [comment]
I agree on renaming IndexDataColumnRef.
Should I open a JIRA for that ?

**Comment by kadirozde** [comment]
> I agree on renaming IndexDataColumnRef. Should I open a JIRA for that ?

Let us do it as part of this Jira.

**Comment by stoty** [comment]
Pushed the rename to the other PR, @kadirozde .

**Pull request closed without merging**
