### PR TITLE
PHOENIX-6841 Depend on omid-codahale-metrics

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by richardantal** [comment]
I think we should add omid-codahale-metrics to the list of ignoredUnusedDeclaredDependencies too

**Comment by richardantal** [comment]
Just realised that we have a line this line to cover everything under org.apache.omid:
https://github.com/apache/phoenix/blob/master/pom.xml#L369

**Comment by stoty** [comment]
Not needed for master, but we don't have the wildcard ignore on 5.1.
I have updated the 5.1 pull request, thank you.

**Comment by stoty** [comment]
Thanks, I'll let the 5.1 PR with the changes complete, then push it.

**Pull request closed without merging**
