### PR TITLE
PHOENIX-7130 Support skipping of shade sources jar creation

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by NihalJain** [comment]
This is a backport of https://github.com/apache/phoenix/pull/1745

**Review by gjacoby126 — APPROVED** [review]
+1

**Comment by NihalJain** [comment]
Rebased code and verified no new instances of createSourcesJar in code. Could you please merge this.?

CC: @gjacoby126 @stoty

**Comment by stoty** [comment]
merged manually.
Note that 5.2 still does not have this.

**Pull request closed without merging**
