### PR TITLE
PHOENIX-6118: Multi Tenant Workloads using PHERF

### PR DESCRIPTION
**Pull request by jpisaac**

### CODE REVIEW

**Comment by jpisaac** [comment]
@yanxinyi @ChinmaySKulkarni

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 41s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 10 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  19m 45s |  master passed  |
| +0 |  hbaserecompile  |  28m 52s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   0m 34s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 35s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 24s |  master passed  |
| +0 :ok: |  spotbugs  |   0m 59s |  phoenix-pherf in master has 42 extant spotbugs warnings.  |
| -0 :warning: |  patch  |   1m  8s |  Used diff version of patch file. Binary files and potentially other changes not applied. Please rebase and squash commits if necessary.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  12m  7s |  the patch passed  |
| +0 |  hbaserecompile  |  21m 42s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   0m 35s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 35s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 47s |  phoenix-pherf: The patch generated 756 new + 929 unchanged - 54 fixed = 1685 total (was 983)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 2 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 1 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m 10s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   0m 23s |  phoenix-pherf generated 25 new + 32 unchanged - 0 fixed = 57 total (was 32)  |
| -1 :x: |  spotbugs  |   1m 11s |  phoenix-pherf generated 9 new + 41 unchanged - 1 fixed = 50 total (was 42)  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  |  11m 17s |  phoenix-pherf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  69m 45s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:phoenix-pherf |
|  |  Found reliance on default encoding in org.apache.phoenix.pherf.util.PhoenixUtil.buildStatement(RulesApplier, Scenario, List, PreparedStatement, SimpleDateFormat):in org.apache.phoenix.pherf.util.PhoenixUtil.buildStatement(RulesApplier, Scenario, List, PreparedStatement, SimpleDateFormat): String.getBytes()  At PhoenixUtil.java:[line 557] |
|  |  input must be non-null but is marked as nullable  At IdleTimeOperationSupplier.java:is marked as nullable  At IdleTimeOperationSupplier.java:[lines 52-74] |
|  |  input must be non-null but is marked as nullable  At PreScenarioOperationSupplier.java:is marked as nullable  At PreScenarioOperationSupplier.java:[lines 51-80] |
|  |  input must be non-null but is marked as nullable  At QueryOperationSupplier.java:is marked as nullable  At QueryOperationSupplier.java:[lines 54-87] |
|  |  Possible null pointer dereference in org.apache.phoenix.pherf.workload.mt.tenantoperation.TenantOperationWorkHandler.onEvent(TenantOperationWorkload$TenantOperationEvent) due to return value of called method  Dereferenced at TenantOperationWorkHandler.java:org.apache.phoenix.pherf.workload.mt.tenantoperation.TenantOperationWorkHandler.onEvent(TenantOperationWorkload$TenantOperationEvent) due to return value of called method  Dereferenced at TenantOperationWorkHandler.java:[line 58] |
|  |  Return value of TenantOperationFactory.getPhoenixUtil() ignored, but method has no side effect  At TenantOperationWorkHandler.java:but method has no side effect  At TenantOperationWorkHandler.java:[line 59] |
|  |  input must be non-null but is marked as nullable  At UpsertOperationSupplier.java:is marked as nullable  At UpsertOperationSupplier.java:[lines 56-136] |
|  |  org.apache.phoenix.pherf.workload.mt.tenantoperation.UpsertOperationSupplier$1.apply(TenantOperationInfo) may fail to clean up java.sql.Statement  Obligation to clean up resource created at UpsertOperationSupplier.java:up java.sql.Statement  Obligation to clean up resource created at UpsertOperationSupplier.java:[line 81] is not discharged |
|  |  input must be non-null but is marked as nullable  At UserDefinedOperationSupplier.java:is marked as nullable  At UserDefinedOperationSupplier.java:[lines 44-46] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1181 |
| JIRA Issue | PHOENIX-6118 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile spotbugs hbaserebuild hbaseanti checkstyle |
| uname | Linux 3096d137a3a1 4.15.0-136-generic #140-Ubuntu SMP Thu Jan 28 05:20:47 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 2a2d996 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-pherf.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/whitespace-eol.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/whitespace-tabs.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/diff-javadoc-javadoc-phoenix-pherf.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/artifact/yetus-general-check/output/new-spotbugs-phoenix-pherf.html |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/testReport/ |
| Max. process+thread count | 1570 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf U: phoenix-pherf |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1181/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by yanxinyi** [comment]
Most likely I will take a look tomorrow, but I want to know why the 4.x branch includes 58 files changes but master has 55 modified files.

**Comment by jpisaac** [comment]
@yanxinyi 
The following files are not included in the master, since they had only import changes and was probably taken care by the cherry-pick merges.

SequentialIntegerDataGenerator.java
MultithreadedDiffer.java
WorkloadExecutor.java

**Review by yanxinyi — APPROVED** [review]

**Pull request merged**
