### PR TITLE
PHOENIX-7230 : Optimize rpc call to master if all indexes are migrated to new coprocs

### PR DESCRIPTION
**Pull request by palashc**

### CODE REVIEW

**Review by virajjasani — APPROVED** [review]
+1, pending jenkins build

**Comment by virajjasani** [comment]
Would like to include with 5.2.0.

**Comment by palashc** [comment]
@virajjasani 2 failures but probably flappers? They pass locally.

**Comment by virajjasani** [comment]
Let me cherry-pick to 5.2 also

**Pull request merged**
