### PR TITLE
PHOENIX-6659 RVC query fix for variable column + fixed column

### PR DESCRIPTION
**Pull request by jpisaac**
Signed-off-by: Gokcen Iskender <gokceng@gmail.com>

### CODE REVIEW

**Comment by jpisaac** [comment]
@gjacoby126 @stoty Please review

**Review by stoty — APPROVED** [review]
I haven't specifically checked this, but as this is a backport, it's goof to go, unless the test results show unexpected errors.

**Comment by gjacoby126** [comment]
@jpisaac - there are InListIT failures, could you please take a look?

**Review by gjacoby126 — CHANGES_REQUESTED** [review]
Let's make sure the InListIT tests are green first.

**Comment by jpisaac** [comment]
@gjacoby126 This backport (PHOENIX-6659) and the backport of (PHOENIX-6662) are needed for the test failures to be green.

**Review by gjacoby126 — APPROVED** [review]
Talked with @jpisaac offline and he explained that the two InListIT failures are the pre-existing ones introduced by the 5.1 backport of PHOENIX-6751. This is the first of 2 PRs to remedy those test failures but we won't get the remediation until the 2nd PR.

**Pull request merged**
