### PR TITLE
PHOENIX-7195 Exclude reload4j dependencies from Hadoop and add explic…

### PR DESCRIPTION
**Pull request by stoty**
…it log4j2 test dependencies

### CODE REVIEW

**Review by virajjasani — COMMENTED** [review]
Since we are excluding reload4j, we need log4j at test scope?

**Comment by stoty** [comment]
We've already switched to log4j2 previously.
I suspect that this was broken during the code refactor, when we forgot to re-add the log4j2 dependencies to phoenix-core.
So that part is just a regression fix.

Recent Hadoop releases has switched for lof4j1 to reload4j, and we haven't filtered that yet, so this is needed to restore the correct logging libraries (log4j2) in case a new Hadoop is used (otherwise we'd have both reload4j and log4j2 jars). This is a net new change.

**Comment by stoty** [comment]
So this is in effect two different fixes rolled into one, one regression fix (re-add log4j2 libs), and one for new Hadoop releases (filter reload4j).

**Review by virajjasani — APPROVED** [review]

**Comment by stoty** [comment]
merged manually.

**Pull request closed without merging**
