### PR TITLE
PHOENIX-5235: Update SQLline version to the latest

### PR DESCRIPTION
**Pull request by swaroopak**

### CODE REVIEW

**Comment by gjacoby126** [comment]
@swaroopak  - sqlline 1.6 and up requires Java 8, which is fine for Phoenix 5.x in the master branch but can't go in the 4.x branches, which still allow for Java 7. Perhaps we could go to 1.5 in the 4.x branches and 1.7 in master?

**Comment by ChinmaySKulkarni** [comment]
+1

**Comment by gjacoby126** [comment]
JIRA is resolved, closing PR.

**Comment by swaroopak** [comment]
check the comment above. @ChinmaySKulkarni @jpisaac

**Pull request closed without merging**
