### PR TITLE
PHOENIX-5103: Can't create/drop table using 4.14 client against 4.15 server

### PR DESCRIPTION
**Pull request by ChinmaySKulkarni**

### CODE REVIEW

**Comment by ChinmaySKulkarni** [comment]
Please review @vincentpoon @twdsilva

**Comment by twdsilva** [comment]
+1

**Comment by vincentpoon** [comment]
+1, thanks @ChinmaySKulkarni

**Comment by ChinmaySKulkarni** [comment]
Thanks for the reviews @twdsilva and @vincentpoon

**Pull request closed without merging**
