### PR TITLE
PHOENIX-7320 Upgrade HBase 2.4 to 2.4.18

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
This needs to be tested locally as the yetus script cannot handle HBase 2.4 version changes.

**Comment by stoty** [comment]
But on the bright side, this is the very last 2.4 version.

**Comment by stoty** [comment]
Come to think of it, we don't even run precommit tests with 2.4 anymore.

**Review by virajjasani — APPROVED** [review]

**Comment by virajjasani** [comment]
Precommit on master builds run with 2.4 tests right?

**Comment by stoty** [comment]
No, it runs with 2.5 now.

**Comment by stoty** [comment]
AFAIR, but I will check again.

**Comment by stoty** [comment]
Yes, we've switched the default profile to 2.5 some time ago.

**Comment by stoty** [comment]
But the tests here fail with 2.5 the same as with 2.4.

I suspect that something has regressed since 5.2.0.

**Comment by virajjasani** [comment]
Sounds good. The precommit build for master branch has run tests against HBase 2.4 profile also, the results look good https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/master/682/testReport/

**Comment by virajjasani** [comment]
> But the tests here fail with 2.5 the same as with 2.4.
> 
> I suspect that something has regressed since 5.2.0.

Yes, some efforts are going on to improve those tests.

**Comment by stoty** [comment]
Interesting, those are not the tests that fail for me locally.
Maybe it depends on machine / storage speed.

**Pull request merged**
