### PR TITLE
PHOENIX-7223  Make Sure Tools Always Close HBase  Connections on Exit

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by virajjasani — APPROVED** [review]

**Comment by virajjasani** [comment]
Shall we include this with 5.2.0?

**Comment by stoty** [comment]
It's only critical ina very specific scenario. (when using Netty in ZK)

It's nice to have, but only if it does not cause you to do extra work, @virajjasani .

**Comment by stoty** [comment]
I've committed this to master now, @virajjasani .
I'm going to set the fixed version to 5.2.0, as I'm not sure if you've cut the 5.2 branch yet.

**Comment by stoty** [comment]
merged manually

**Comment by virajjasani** [comment]
5.2 branch is cut, will cherry-pick this.

**Comment by virajjasani** [comment]
Though I still need to bump master branch's version to 5.3.0 to effectively distinguish master and 5.2 branches.

**Pull request closed without merging**
