### PR TITLE
PHOENIX-6707 Use Configuration.getLongBytes where applicable

### PR DESCRIPTION
**Pull request by anmolnar**
I tried to find all the applicable places for the replacement. Please verify.

### CODE REVIEW

**Comment by stoty** [comment]
Most preoperties are defined in QueryServicesOptions , I can see a bunch of further candidates there.

**Comment by anmolnar** [comment]
@stoty I'm not sure what do you mean by "in QueryServices". That's an interface which doesn't have logic.
In most places I see something like the following:

```
                    connection
                            .getQueryServices()
                            .getProps()
                            .getLong(QueryServices.SEQUENCE_CACHE_SIZE_ATTRIB,
                                QueryServicesOptions.DEFAULT_SEQUENCE_CACHE_SIZE);
```

getProps() gives you `ReadOnlyProps` which doesn't have getLongBytes alternative.

**Comment by anmolnar** [comment]
@stoty Thanks for the pointer. I've found a couple of more.

**Comment by stoty** [comment]
Come to think of it, implementing getLongBytes on ReadOnlyProps would probably be a good idea.

**Comment by anmolnar** [comment]
@stoty I've implemented getLongBytes() for `ReadOnlyProps` and rebased the patch. PTAL.

**Comment by stoty** [comment]
Mostly looks good.
Can you add a small UT for getLongBytes()  in ReadOnlyProps to improve test coverage ?

**Review by stoty — APPROVED** [review]
+1 LGTM

**Pull request closed without merging**
