### PR TITLE
PHOENIX-6480 Move phoenix-tool and add support with generating defaul…

### PR DESCRIPTION
**Pull request by gokceni**
…t properties

### CODE REVIEW

**Comment by gokceni** [comment]
@swaroopak

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 24s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   8m 57s |  root in 4.x failed.  |
| -1 :x: |  compile  |   1m 26s |  root in 4.x failed.  |
| -1 :x: |  checkstyle  |   0m 44s |  The patch fails to run checkstyle in root  |
| -1 :x: |  javadoc  |   1m 10s |  root in 4.x failed.  |
| -1 :x: |  spotbugs  |   4m  7s |  root in 4.x failed.  |
| +0 :ok: |  spotbugs  |   3m  1s |  phoenix-core in 4.x has 951 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 43s |  phoenix-tools in 4.x has 5 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 17s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   5m 25s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 24s |  root in the patch failed.  |
| -1 :x: |  javac  |   1m 24s |  root in the patch failed.  |
| -1 :x: |  checkstyle  |   0m 43s |  The patch fails to run checkstyle in root  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 2 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   1m  5s |  root in the patch failed.  |
| -1 :x: |  spotbugs  |   3m 15s |  phoenix-core generated 7 new + 951 unchanged - 0 fixed = 958 total (was 951)  |
| -1 :x: |  spotbugs  |   3m 59s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 149m 18s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 21s |  The patch does not generate ASF License warnings.  |
|  |   | 194m 55s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:phoenix-core |
|  |  Found reliance on default encoding in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String):in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String): new java.io.FileReader(File)  At SchemaSynthesisProcessor.java:[line 211] |
|  |  Null passed for non-null parameter of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:[line 80] |
|  |  Null passed for non-null parameter of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:[line 81] |
|  |  org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String) may fail to close stream  At SchemaSynthesisProcessor.java:stream  At SchemaSynthesisProcessor.java:[line 211] |
|  |  org.apache.phoenix.schema.tool.SchemaTool.conf should be package protected  In SchemaTool.java: In SchemaTool.java |
|  |  Possible null pointer dereference of cmdLine in org.apache.phoenix.schema.tool.SchemaTool.parseOptions(String[])  Dereferenced at SchemaTool.java:cmdLine in org.apache.phoenix.schema.tool.SchemaTool.parseOptions(String[])  Dereferenced at SchemaTool.java:[line 114] |
|  |  Write to static field org.apache.phoenix.schema.tool.SchemaTool.conf from instance method org.apache.phoenix.schema.tool.SchemaTool.run(String[])  At SchemaTool.java:from instance method org.apache.phoenix.schema.tool.SchemaTool.run(String[])  At SchemaTool.java:[line 73] |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1245 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile xml |
| uname | Linux a7c9b46ed1f8 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / b42a25b |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/branch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/buildtool-branch-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/branch-javadoc-root.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/branch-spotbugs-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/buildtool-patch-checkstyle-root.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/whitespace-tabs.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-javadoc-root.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/new-spotbugs-phoenix-core.html |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-spotbugs-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/testReport/ |
| Max. process+thread count | 5709 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by swaroopak — COMMENTED** [review]
Thank you for the change. Could you please also add a test?

**Review by swaroopak — APPROVED** [review]
LGTM Thanks!

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +0 :ok: |  mvndep  |   5m 22s |  Maven dependency ordering for branch  |
| -1 :x: |  mvninstall  |   9m  1s |  root in 4.x failed.  |
| -1 :x: |  compile  |   1m 26s |  root in 4.x failed.  |
| -1 :x: |  checkstyle  |   0m 44s |  The patch fails to run checkstyle in root  |
| -1 :x: |  javadoc  |   1m 10s |  root in 4.x failed.  |
| -1 :x: |  spotbugs  |   4m 17s |  root in 4.x failed.  |
| +0 :ok: |  spotbugs  |   2m 55s |  phoenix-core in 4.x has 951 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 41s |  phoenix-tools in 4.x has 5 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 19s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |   5m 48s |  root in the patch failed.  |
| -1 :x: |  compile  |   1m 24s |  root in the patch failed.  |
| -1 :x: |  javac  |   1m 24s |  root in the patch failed.  |
| -1 :x: |  checkstyle  |   0m 44s |  The patch fails to run checkstyle in root  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 2 line(s) with tabs.  |
| +1 :green_heart: |  xml  |   0m  1s |  The patch has no ill-formed XML file.  |
| -1 :x: |  javadoc  |   1m  5s |  root in the patch failed.  |
| -1 :x: |  spotbugs  |   3m 16s |  phoenix-core generated 7 new + 951 unchanged - 0 fixed = 958 total (was 951)  |
| -1 :x: |  spotbugs  |   3m 55s |  root in the patch failed.  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 138m 55s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 42s |  The patch does not generate ASF License warnings.  |
|  |   | 188m 18s |   |


| Reason | Tests |
|-------:|:------|
| FindBugs | module:phoenix-core |
|  |  Found reliance on default encoding in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String):in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String): new java.io.FileReader(File)  At SchemaSynthesisProcessor.java:[line 211] |
|  |  Null passed for non-null parameter of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:[line 80] |
|  |  Null passed for non-null parameter of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:of new org.apache.phoenix.parse.SQLParser(String) in org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.synthesize(String, String)  Method invoked at SchemaSynthesisProcessor.java:[line 81] |
|  |  org.apache.phoenix.schema.tool.SchemaSynthesisProcessor.getQueriesFromFile(String) may fail to close stream  At SchemaSynthesisProcessor.java:stream  At SchemaSynthesisProcessor.java:[line 211] |
|  |  org.apache.phoenix.schema.tool.SchemaTool.conf should be package protected  In SchemaTool.java: In SchemaTool.java |
|  |  Possible null pointer dereference of cmdLine in org.apache.phoenix.schema.tool.SchemaTool.parseOptions(String[])  Dereferenced at SchemaTool.java:cmdLine in org.apache.phoenix.schema.tool.SchemaTool.parseOptions(String[])  Dereferenced at SchemaTool.java:[line 114] |
|  |  Write to static field org.apache.phoenix.schema.tool.SchemaTool.conf from instance method org.apache.phoenix.schema.tool.SchemaTool.run(String[])  At SchemaTool.java:from instance method org.apache.phoenix.schema.tool.SchemaTool.run(String[])  At SchemaTool.java:[line 73] |
| Failed junit tests | phoenix.end2end.AuditLoggingIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1245 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile xml |
| uname | Linux 3f67cc9f8a42 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / b42a25b |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/branch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/branch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/buildtool-branch-checkstyle-root.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/branch-javadoc-root.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/branch-spotbugs-root.txt |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| compile | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-compile-root.txt |
| javac | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-compile-root.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/buildtool-patch-checkstyle-root.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/whitespace-tabs.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-javadoc-root.txt |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/new-spotbugs-phoenix-core.html |
| spotbugs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-spotbugs-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/testReport/ |
| Max. process+thread count | 5860 (vs. ulimit of 30000) |
| modules | C: phoenix-core . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1245/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
