### PR TITLE
 phoenix.schema.isNamespaceMappingEnabled set true

### PR DESCRIPTION
**Pull request by gurpreet0909**
we have  phoenix.schema.isNamespaceMappingEnabled enable, while running Phoenix MR jar this is the problem we are getting and there is no way to solve it.

### CODE REVIEW

**Comment by gjacoby126** [comment]
@gurpreet0909 - I believe this patch would break MapReduce jobs that do not have isNamespaceMappingEnabled set to true. (You can see, for example, that in the Jenkins test run that TableSnapshotReadsMapReduceIT has several failures for this reason.) 

Shouldn't we only set the MapReduce client to isNamespaceMappingEnabled = true if the cluster is in fact namespace enabled?

**Comment by gurpreet0909** [comment]
> @gurpreet0909 - I believe this patch would break MapReduce jobs that do not have isNamespaceMappingEnabled set to true. (You can see, for example, that in the Jenkins test run that TableSnapshotReadsMapReduceIT has several failures for this reason.)
> 
> Shouldn't we only set the MapReduce client to isNamespaceMappingEnabled = true if the cluster is in fact namespace enabled?

Hi, i am using these jars in client side only in my Mapreduce jar which i am running on hdfs, but the problem is my MapReduce jar is going the hit this jar class for connection at the same place where i have added the property in the commit. For me there is not way to inject this property inside these jars,

i have tried to create custom jar but since its maven project it needs to download dependencies from repository for which i am not authenticated. 

How do i solve it then?

**Comment by stoty** [comment]
Having matching hbase-site.xml s on the server side and client (MR) side is non negotiatieble.
You can either:
- Add the hbase-site.xml to the JAR that contains jour MR job
- Package hbase-site.xml to a separate JAR, and add that to you job
- Distribute the hbase-side the hbase-site.xml everywhere and the directory

**Review by stoty — CHANGES_REQUESTED** [review]
-2

**Pull request closed without merging**
