### PR TITLE
Build the HBase 2.5+ profiles with Hadoop 3.3.6

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
Need to run some tests to see if the minicluster binaries can handle the newer Hadoop (especially for 2.5.0 and 2.4)

**Comment by stoty** [comment]
2.4 tests fail with Hadoop 3.3 because of the known minicluster incompatibilities, but mixing Hadoop 3.2 and 3.3 does not cause any test failures.

2.4 is EOL anyway.

**Comment by virajjasani** [comment]
Do we need to run all tests for 2.5 and 2.6 profiles? or let precommit builds run it?

**Review by virajjasani — APPROVED** [review]
+1, pending Jira title

**Comment by stoty** [comment]
I have run the test for 2.5 manually, and did not see more than the usual failures @virajjasani .
2.6 is tested by the precommit job.

**Comment by stoty** [comment]
I did not realize I missed the JIRA ID from the commit message, thanks for catching that.

**Comment by stoty** [comment]
merged manually

**Pull request closed without merging**
