### PR TITLE
PHOENIX-4688 Kerberize python phoenixdb -- Phoenix 5

### PR DESCRIPTION
**Pull request by pu239ppy**
Lets rip out httplib and replace with requests and use requests kerberos

#### Notes
- Will not work out of the box, since requires virtualenv on anaconda
- Excluded the IT from list, needs to be invoked manually
`mvn -Dit.test=org.apache.phoenix.end2end.SecureQueryServerPhoenixDBIT verify`

#### Standalone install
This is currently a manual procedure with a few steps due to the current version not being in a public pipy and also the fact that we had to fork requests-kerberos
1. Create a python virtual environment by calling `conda create` or `virtual-env`
2. . activate the virtual environment
3. pip install -e phoenix/python/requests-kerberos
4. pip install -e phoenix/python/phoenixdb-module
5. You need kerberos credentials run kinit
6. Run a python program to access a DB similar to one below
7. Profit

#### Example script
````python
import phoenixdb
import phoenixdb.cursor
import sys


if __name__ == '__main__':
    pqs_port = sys.argv[1]
    database_url = 'http://localhost:' + str(pqs_port) + '/'

    print "CREATING PQS CONNECTION"
    conn = phoenixdb.connect(database_url, autocommit=True, auth="SPNEGO")
    cursor = conn.cursor()

    cursor.execute("CREATE TABLE users (id INTEGER PRIMARY KEY, username VARCHAR)")
    cursor.execute("UPSERT INTO users VALUES (?, ?)", (1, 'admin'))
    cursor.execute("UPSERT INTO users VALUES (?, ?)", (2, 'user'))
    cursor.execute("SELECT * FROM users")
    print cursor.fetchall()
````

Replaces #307

### CODE REVIEW

**Comment by joshelser** [comment]
This looks awesome, @pu239ppy. Testing it out.

**Comment by akhmadMizkat** [comment]
> This looks awesome, @pu239ppy. Testing it out.

Hi @joshelser , did you finally managed to test it out successfully?

**Comment by pu239ppy** [comment]
@akhmadMizkat this solution currently does not work, please see latest commentary on PHOENIX-4688 for description.  There are existing solutions to remediate this, however I was hoping not to distibute a patched version of requests-kerberos

**Comment by akhmadMizkat** [comment]
@pu239ppy thank you for the clarification. Hope they can accept your PR on the requests-kerberos. Really looking forward for that.

**Comment by joshelser** [comment]
> Hi @joshelser , did you finally managed to test it out successfully?

No, sadly. I didn't get the last variant working. Pulling down this version and trying again.

**Comment by joshelser** [comment]
```
2018-09-27 14:05:06,308 ERROR [main] end2end.SecureQueryServerPhoenixDBIT(358): + python /Users/jelser/projects/phoenix.git/phoenix-queryserver/./src/it/bin/test_phoenixdb.py 50023
2018-09-27 14:05:06,309 ERROR [main] end2end.SecureQueryServerPhoenixDBIT(358): /Users/jelser/projects/phoenix.git/phoenix-queryserver/./src/it/bin/test_phoenixdb.sh: line 60:  7582 Illegal instruction: 4  python $PYTHON_SCRIPT $PQS_PORT
```

We're back to this junk again. @pu239ppy what version of Python are you running for which this is working?

**Comment by joshelser** [comment]
Ok, with python 3.6.5, downgrading to pykerberos to 1.1.14 (in requests-kerberos), and updating test_phoenixdb.py for python3 print syntax, it works!!!

**Comment by joshelser** [comment]
Oops, forgot one more thing. I changed the integration test that had heimdal syntax because, even though I have OSX, I have MIT Kerberos installed.

Although, now that I think about it, do we need to generate a specific krb5.conf based on OS at all? The embedded KDC is provided by Kerby from Apache Directory -- it's not Heimdal or MIT Kerberos. That can be cleaned up completely.

@pu239ppy let me know. I can send a pull request to your branch if you're ready to just be done with these changes. I want to poke around some more at Python versions that work locally.

**Comment by akhmadMizkat** [comment]
Awesome guys. This is a very good improvement for the phoenixdb library.

**Comment by Reidddddd** [comment]
Python version has to >= 3.6.5? 
@joshelser @pu239ppy

**Comment by joshelser** [comment]
Hey @Reidddddd -- likely other version of Python will work too, we just only tested using 3.6.5

**Pull request closed without merging**
