### PR TITLE
PHOENIX-6755 SystemCatalogRegionObserver extends BaseRegionObserver w…

### PR DESCRIPTION
**Pull request by shahrs87**
…hich doesn't exist in hbase-2.4 branch.

### CODE REVIEW

**Review by stoty — APPROVED** [review]
+1 LGTM

**Comment by shahrs87** [comment]
The following tests are failing in jenkins build. It is failing even in master branch without my patch. It is failing to bring up datanode. Created [PHOENIX-6757](https://issues.apache.org/jira/browse/PHOENIX-6757) to track these failures.
```
[ERROR] Failures: 
[ERROR]   IndexToolForNonTxGlobalIndexIT.testSecondaryGlobalIndexFailure:385 expected:<-1> but was:<0>
[ERROR]   IndexToolForNonTxGlobalIndexIT.testSecondaryGlobalIndexFailure:385 expected:<-1> but was:<0>
[ERROR] Errors: 
[ERROR]   BackwardCompatibilityIT.testViewIndexIdCreatedWithOldClient:428 Â» SQL ERROR 20...
[ERROR]   ViewIndexIdRetrieveIT.testMixedCase:145 Â» SQL ERROR 201 (22000): Illegal data....
[ERROR]   ViewIndexIdRetrieveIT.testSelectViewIndexIdAsShort:80->testSelectViewIndexId:103 Â» SQL
[INFO] 
[ERROR] Tests run: 1610, Failures: 2, Errors: 3, Skipped: 65
```

**Comment by virajjasani** [comment]
Retriggered the tests on the build.

**Review by virajjasani — COMMENTED** [review]
Can we also make it implement `RegionCoprocessor`?

**Comment by virajjasani** [comment]
And we can put this method:
```
    @Override
    public Optional getRegionObserver() {
        return Optional.of(this);
    }

```

**Review by virajjasani — APPROVED** [review]
+1, pending QA

**Comment by virajjasani** [comment]
Build in-progress: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1472/3/

**Comment by shahrs87** [comment]
All the tests succeeded in the latest run. The asf license warning is not related to my patch.
Cc @virajjasani

**Comment by virajjasani** [comment]
Thank you @shahrs87

**Pull request merged**
