### PR TITLE
[PHOENIX-3061] IndexTool exits 0 even if bulkload failed with error

### PR DESCRIPTION
**Pull request by SsnL**
**What**:
Fix such that when the MapReduce job fails, the job exits with non-zero code and logs meaningful error message.

**How**:
Modified `IndexTool.configureSubmittableJobUsingDirectApi` and `IndexTool.configureRunnableJobUsingBulkLoad` so that they don't swallow errors.

### CODE REVIEW

**Comment by JamesRTaylor** [comment]
@gabrielreid or @SergeySoldatov - would you have a few spare cycles to review this small patch?

**Comment by SsnL** [comment]
Reverted deleting reducer class.

The tests still fail when `directAPI` and `transactional` are both set.

@twdsilva any ideas?

**Comment by twdsilva** [comment]
Looking into this now.

**Comment by SsnL** [comment]
@twdsilva comes to save the day. 16/16 tests pass!

**Pull request closed without merging**
