### PR TITLE
PHOENIX-6322 hasPreWALAppend() returns false for HBase 2.3 and 2.4

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 35s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  13m 52s |  master passed  |
| +0 |  hbaserecompile  |  25m 18s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 33s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 39s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 39s |  master passed  |
| +0 :ok: |  spotbugs  |   0m 37s |  phoenix-hbase-compat-2.4.0 in master has 1 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 33s |  phoenix-hbase-compat-2.3.0 in master has 1 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m  8s |  the patch passed  |
| +0 |  hbaserecompile  |  14m 40s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 34s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 34s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 37s |  root: The patch generated 2 new + 16 unchanged - 2 fixed = 18 total (was 18)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 39s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   1m 30s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 114m 35s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 173m 17s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.ToDateFunctionIT |
|   | phoenix.end2end.WALAnnotationIT |
|   | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1094 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 9fc960992a97 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 50df995 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/1/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/1/testReport/ |
| Max. process+thread count | 13037 (vs. ulimit of 30000) |
| modules | C: phoenix-hbase-compat-2.4.0 phoenix-hbase-compat-2.3.0 U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by dbwong — APPROVED** [review]

**Review by gjacoby126 — APPROVED** [review]
+1, thanks @stoty

**Comment by stoty** [comment]
In the previous version WALAnnotationIT failed, because for HBase 2 WALObserver must be wrapped in a WALCodec.
Care to take another look at the fixed patch @dbwong , @gjacoby126 ?

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 33s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  11m 11s |  master passed  |
| +0 |  hbaserecompile  |  22m 29s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 31s |  master passed  |
| +1 :green_heart: |  checkstyle  |   0m 37s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 30s |  master passed  |
| +0 :ok: |  spotbugs  |   0m 35s |  phoenix-hbase-compat-2.4.0 in master has 1 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 36s |  phoenix-hbase-compat-2.3.0 in master has 1 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   2m 58s |  phoenix-core in master has 955 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 11s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 20s |  the patch passed  |
| +0 |  hbaserecompile  |  15m  9s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 31s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 31s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 38s |  root: The patch generated 2 new + 16 unchanged - 2 fixed = 18 total (was 18)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m 31s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m 51s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 114m 22s |  root in the patch failed.  |
| +1 :green_heart: |  asflicense  |   1m 56s |  The patch does not generate ASF License warnings.  |
|  |   | 174m 40s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1094 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 283f21e783fb 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / e19cc3f |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/2/artifact/yetus-general-check/output/diff-checkstyle-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/2/testReport/ |
| Max. process+thread count | 13198 (vs. ulimit of 30000) |
| modules | C: phoenix-hbase-compat-2.4.0 phoenix-hbase-compat-2.3.0 phoenix-core U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1094/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by gjacoby126 — APPROVED** [review]
Thanks for catching the NPE, @stoty .

**Pull request closed without merging**
