### PR TITLE
PHOENIX-1071 Add phoenix-spark for Spark integration

### PR DESCRIPTION
**Pull request by jmahonin**
This adds a new module which can be used to load and save Phoenix tables through the Spark 1.3.0+ DataFrame and RDD APIs.

It's based originally on https://github.com/simplymeasured/phoenix-spark with significant modifications to bump the Phoenix and Spark dependencies, and also adds the write() implementation to PhoenixRecordWritable

Usage examples and further documentation can be found in README.md. Even more usage examples can be found in PhoenixRDDTest.

I've attempted to adhere to the ASF guidelines, adding the appropriate headers and attribution in NOTICE. I'm not entirely clear on the guidelines for moving Copyright notices from original source files, but I've contacted the Simply Measured folks for approval to do so, if necessary.

I also have branch which merges on the 4.3 branch I've been using internally, which I can submit as well. The only merge conflicts are the NOTICE file, the modules listed in /pom.xml, and the parent POM version in /phoenix-spark/pom.xml

Please let me know if there's anything more I can provide in terms of explanation, documentation, testing, etc.

### CODE REVIEW

**Comment by JamesRTaylor** [comment]
Good stuff, @jmahonin. Thanks so much for the contribution. Any Spark experts out there that can review this? @apurtell ?

**Comment by mravi** [comment]
Nice work @jmahonin .  Couple of minor changes

1.  JDK version in the pom.xml is 1.8. You would need to downgrade to 1.7
2.  For the ProductRDDFunctions.scala file, I notice a mismatch in the package declaration.
3. Would be ideal if we could have a scala file say PhoenixSparkContext that merges the functionality you have written in ProductRDDFunctions and  SparkContextFunctions .
4. Renaming SparkSqlContextFunctions to just PhoenixSparkSqlContext to make easier for end users.
5. The build goes through fine but when I try to run the PhoenixRDDTest from a ScalaIDE , I keep getting errors. It could be more of a IDE thing which i will fix and get back on tests results. 

Good to haves
1. A Java friendly version of the PhoenixSparkContext and PhoenixSparkSqlContext classes for a easier adoption for java folks ( like me :) )
2. Extend the org.apache.spark.sql.sources.RelationProvider  and have PhoenixDatasource.

**Comment by jmahonin** [comment]
Thanks for the feedback @mravi , point comments below:

1: Right, I'll try get that sorted out. The original phoenix-spark library would not work with 1.7 for some reason, but that may no longer be the case.

2: Good catch. I think IntelliJ did something a little funny here on me, that file was supposed to be in the main hierarchy.

3 / 4: It's my first kick at extending Spark (and Phoenix for that matter), but the naming scheme and file separation was modelled off of DataStax' Spark-Cassandra connector, which I figured is as good a model as any:
https://github.com/datastax/spark-cassandra-connector/tree/master/spark-cassandra-connector/src/main/scala/com/datastax/spark/connector

In theory, doing it that way means a user can have just one import to get all the nice implicit definitions:
`import org.apache.spark.phoenix._`

5: I've never had much luck with getting the Scala integration working well on any IDE, I just run 'mvn test' from the CLI.

Re: Good to haves
1. I totally agree, but I don't think I can afford the cycles at the moment. My hope was that by modelling after the spark-cassandra-connector, it would be relatively painless to add for either a third party, or myself in the hopefully not-too-distant-future.
2. Great idea, I hadn't actually seen that usage with Spark SQL yet. We're still using the RDD API internally. On a quick glance it looks fairly straight-forward to implement.

**Comment by mravi** [comment]
@jmahonin  I can join forces with you on the Good to haves

**Comment by jmahonin** [comment]
@mravi Great. I can get 1 and 2 taken care of today.

Are new commits on this PR fine, or would you prefer a new PR with a rebased commit?

**Comment by jmahonin** [comment]
JDK 1.7 and the ProductRDDFunctions package location have been fixed up.

I tried to make some headway on getting the unit tests to run in the IDE. If you're seeing the same errors I am, it may be because you're using OS X. 

There's a "Netty transport" bind error, which can be solved by adding "SPARK_LOCAL_IP=127.0.0.1" to the environment variables. However, after's fixed that I end up with HBase minicluster bind errors. There seem to be instructions here to fix those, which should also solve the Netty issue above, but it hasn't worked for me at all:
http://stackoverflow.com/questions/18717681/hbasetestingutility-could-not-start-my-mini-cluster

**Comment by apurtell** [comment]
I'm not a Spark expert @JamesRTaylor  . I skimmed the latest. Allowing builds with JDK 1.7 would have been the big change I'd have recommended, and it's already been done.

I checked out this PR and ran a build, which completed. I was able to run the unit tests of the new module from the Maven command line, on Linux FWIW:

    $ mvn -DskipTests clean install
    $ mvn test -rf :phoenix-spark 
    [...]
    - Can create valid SQL
    - Can convert Phoenix schema
    - Can create schema RDD and execute query
    - Can create schema RDD and execute query on case sensitive table (no config)
    - Can create schema RDD and execute constrained query
    - Using a predicate referring to a non-existent column should fail
    - Can create schema RDD with predicate that will never match
    - Can create schema RDD with complex predicate
    - Can query an array table
    - Can read a table as an RDD
    - Can save to phoenix table
    - Can save Java and Joda dates to Phoenix (no config)
    - Not specifying a zkUrl or a config quorum URL should fail
    Run completed in 1 minute, 12 seconds.
    Total number of tests run: 13
    Suites: completed 2, aborted 0
    Tests: succeeded 13, failed 0, canceled 0, ignored 0, pending 0
    All tests passed.

With 7u75 I run out of PermGen running PhoenixRDDTest, but fixed that:

    diff --git a/phoenix-spark/pom.xml b/phoenix-spark/pom.xml
     index 5c0c754..21baa16 100644
    --- a/phoenix-spark/pom.xml
    +++ b/phoenix-spark/pom.xml
    @@ -503,6 +503,7 @@
                 <configuration>
                   <parallel>true</parallel>
                   <tagsToExclude>Integration-Test</tagsToExclude>
    +              <argLine>-Xmx3g -XX:MaxPermSize=512m -XX:ReservedCodeCacheSize=51
                 </configuration>
               </execution>
               <execution>

The unit tests are not robust against parallel execution with other HBase or Phoenix test suite invocations on the same host, but this can be fixed with a followup issue with random ports and rebinding 

LGTM for a commit to trunk with some minor follow-ups. 

> Extend the org.apache.spark.sql.sources.RelationProvider and have PhoenixDatasource.

Maybe we should split this work up. The integration as-is is directly useful on its own. The SparkSQL integration nice-to-have can be additional work on a new JIRA / PR?

**Comment by robdaemon** [comment]
So happy to see this go in. I'll push on my former colleagues at Simply Measured about the copyrights!!

**Comment by dacort** [comment]
Consider me poked! Will take a look at this and follow up tomorrow by the latest.

**Comment by jmahonin** [comment]
Can confirm the memory settings needed adjustment on 7u76 on Linux.

Special thanks to @robdaemon who had an excellent library to work with, and a pre-emptive thanks to @dacort for the copyrights!

My preference would be to put the RelationProvider work under a new ticket. It's separate functionality, and although I've made a bit of headway there, testing against the current SparkSQLContext API is yielding some bizarre results. 

It's fairly likely I'm doing something wrong, but that's a brand new API for Spark. Most of the methods have @DeveloperAPI annotations (read: unstable), and a number of fixes are slated for Spark SQL in 1.3.1, so I expect a bit of churn in that area for the time being.

**Comment by dacort** [comment]
@jmahonin Thanks for this PR!

You're good to go with respect to copyrights. Thanks for putting those in the appropriate place.

**Comment by jmahonin** [comment]
I was able to spend a bit more time on the RelationProvider work. The DDL for custom providers doesn't work through the 'sql()' method on SparkSQLContext, perhaps by design or perhaps due to a bug, but the 'load()' method does work to create DataFrames using arbitrary data sources.

I'm still not entirely familiar with their API, and a lot of it is still very new and probably subject to churn, but I tried to base the it on existing examples in the Spark repo, such as the JDBC and Parquet data sources.

I've got a new commit on a side branch here:
https://github.com/FileTrek/phoenix/commit/16f4540ef0889fc6534c91b8638c16001114ba1a

If you're all OK with those changes going in on this PR, I can push them up here. Otherwise, I'll stash them aside for a new ticket.

**Comment by mravi** [comment]
@jmahonin  Let's have the changes for registering as a data source in a separate JIRA. The changes to this commit LGTM.

**Comment by jmahonin** [comment]
@mravi Sounds good. FYI, I was able to run the PhoenixRDDTests in IntelliJ on Linux with no modifications using the 'ScalaTest' configuration.

In summary, I think these are the follow-up tasks that need tickets:
- Support parallel execution in phoenix-spark unit tests
- Add support for Spark data source to phoenix-spark module
- Add Java API for phoenix-spark

I can put those into JIRA if needed.

**Comment by mravi** [comment]
@jmahonin Thanks for the nice work !! I have pushed these changes to 4.X and master branch.

**Pull request closed without merging**
