### PR TITLE
PHOENIX-6754 Upgrades from pre 4.10 versions are broken again

### PR DESCRIPTION
**Pull request by richardantal**

### CODE REVIEW

**Review by stoty — CHANGES_REQUESTED** [review]
This looks like only haf of the fix.
You also need to restore the code that uses the ALTER_SYSCATALOG_TABLE_UPGRADE statement for upgrades.

**Comment by stoty** [comment]
It has been removed from the addColumnMutation() setup, and the addColumnMutation() method.

**Comment by richardantal** [comment]
Thank stoty, Let me update the PR

**Comment by stoty** [comment]
As we have no IT for it, the real test is to manully take a dump of a skeleton Phonix 4.7 install, load it, and test if the upgrade is successful.

**Comment by stoty** [comment]
I like that you put the logic inside the addColumnMutationInternal() method.
LGTM, but let's add the test that we've discussed offline.

**Review by stoty — APPROVED** [review]
As discussed, the test is going to be added in a different commit.

**Comment by richardantal** [comment]
Thank you for the review.

**Pull request merged**
