### PR TITLE
PHOENIX-6232

### PR DESCRIPTION
**Pull request by comnetwork**

### CODE REVIEW

**Comment by symat** [comment]
I can not comment on the code (I'm not familiar with Phoenix internals) but I executed the original production query that failed for us before the patch, and after applying this patch the query succeed. Thanks for the fix!

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m  7s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 2 new or modified test files.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  11m 16s |  4.x passed  |
| +1 :green_heart: |  compile  |   0m 55s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   1m 33s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 43s |  4.x passed  |
| +0 :ok: |  spotbugs  |   2m 56s |  phoenix-core in 4.x has 950 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 24s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 55s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 55s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 39s |  phoenix-core: The patch generated 121 new + 2612 unchanged - 83 fixed = 2733 total (was 2695)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| -1 :x: |  javadoc  |   0m 41s |  phoenix-core generated 1 new + 99 unchanged - 1 fixed = 100 total (was 100)  |
| +1 :green_heart: |  spotbugs  |   3m  6s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 206m 57s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  The patch does not generate ASF License warnings.  |
|  |   | 244m 42s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.PointInTimeQueryIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.40 ServerAPI=1.40 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/992 |
| JIRA Issue | PHOENIX-6232 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux a25f0bde3789 4.15.0-65-generic #74-Ubuntu SMP Tue Sep 17 17:06:04 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 18b9f76 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/artifact/yetus-general-check/output/diff-javadoc-javadoc-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/testReport/ |
| Max. process+thread count | 6170 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-992/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by dbwong** [comment]
Can we close this PR? I see the code in 4.x and I see https://issues.apache.org/jira/browse/PHOENIX-6232 is marked as resolved.

**Comment by comnetwork** [comment]
Yes，I would close it.

**Pull request closed without merging**
