### PR TITLE
Sync 4.x-HBase-1.2 to master

### PR DESCRIPTION
**Pull request by pboado**
This PR syncs 4.x-HBase-1.2 to master branch

### CODE REVIEW

**Comment by JamesRTaylor** [comment]
I pushed this to 4.x-HBase-1.2

**Comment by pboado** [comment]
I don't really think it's a great idea squashing all commits for this PR, it makes really difficult to track what has been merged and what hasn't from master . Could you please  reverse/rebase the branch and apply the pull request instead?

**Comment by JamesRTaylor** [comment]
Agreed, but the github repo is read-only so the PR can’t be manually applied. The only way I know how to do this is by manually cherry picking the commits (and manually resolving any conflicts). Only committers are able to do this, though. Otherwise, you could create separate patches for any commits that don’t cherry pick cleanly. Let me know and I can revert my previous commit.

**Comment by pboado** [comment]
Yes James, please revert the commit and I'll attach a set of patches to be applied -almost all cherry picks applied with no conflicts-

**Comment by JamesRTaylor** [comment]
You can attach patch (to original JIRA) only when the cherry pick doesn’t apply cleanly - that’s probably easiest.

**Comment by pboado** [comment]
I think I found a way of applying the changes. I've just uploaded all files generated by `git format-patch HEAD~14` to the JIRA ticket. By downloading them into the same folders and running a `git-am *.patch` patches should be applied in the right order keeping original author and commit times.

**Comment by pboado** [comment]
Same patches here compressed into a .tar.gz file - easier to download - 
[PR-286.tar.gz](https://github.com/apache/phoenix/files/1565194/PR-286.tar.gz)

**Comment by stoty** [comment]
This may or may not have been applied, but is definitely no longer relevant.
Closing.

**Pull request closed without merging**
