### PR TITLE
PHOENIX-6953 Creating indexes on a table with old indexing leads to i…

### PR DESCRIPTION
**Pull request by stoty**
…nconsistent co-processors

### CODE REVIEW

**Review by gjacoby126 — CHANGES_REQUESTED** [review]
Change looks OK, but there are test failures on GlobalMutableTxIndexIT and UpsertSelectIT that look related.

**Review by gjacoby126 — CHANGES_REQUESTED** [review]
Change looks OK, but there are test failures on GlobalMutableTxIndexIT and UpsertSelectIT that look related.

**Comment by stoty** [comment]
I was unable to repro those, and I'm pretty sure both are unrelated

**Comment by stoty** [comment]
However, we also call the function from updateDescriptorForTx(), and that one didn't check for old vs new indexing.
It doesn't matter for the current master, as changing transactional status is disabled in both directions, but it may matter for an 5.1 backport, or in the future when it is re-enabled.
Please take another look, @gjacoby126 .

**Pull request closed without merging**
