### PR TITLE
PHOENIX-6343 : Phoenix allows duplicate column names when one of them is a primary key

### PR DESCRIPTION
**Pull request by virajjasani**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 23s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 11s |  master passed  |
| +0 |  hbaserecompile  |  24m 10s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  4s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 17s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 53s |  master passed  |
| +0 :ok: |  spotbugs  |   3m 17s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  10m 13s |  the patch passed  |
| +0 |  hbaserecompile  |  21m 24s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 16s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 16s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 30s |  phoenix-core: The patch generated 1 new + 2869 unchanged - 0 fixed = 2870 total (was 2869)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m  1s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   4m  2s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   2m  1s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   |  66m  1s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.compile.SelectStatementRewriterTest |
|   | phoenix.query.ExplainPlanTextTest |
|   | phoenix.util.json.JsonUpsertExecutorTest |
|   | phoenix.schema.MutationTest |
|   | phoenix.jdbc.PhoenixDriverTest |
|   | phoenix.compile.QueryMetaDataTest |
|   | phoenix.compile.PostIndexDDLCompilerTest |
|   | phoenix.index.VerifySingleIndexRowTest |
|   | phoenix.query.ParallelIteratorsSplitTest |
|   | phoenix.compile.WhereCompilerTest |
|   | phoenix.compile.CursorCompilerTest |
|   | phoenix.query.QueryPlanTest |
|   | phoenix.compile.JoinQueryCompilerTest |
|   | phoenix.query.OrderByTest |
|   | phoenix.util.ScanUtilTest |
|   | phoenix.query.PropertyPolicyProviderTest |
|   | phoenix.schema.RowKeySchemaTest |
|   | phoenix.expression.NullValueTest |
|   | phoenix.iterate.RowKeyOrderedAggregateResultIteratorTest |
|   | phoenix.compile.ViewCompilerTest |
|   | phoenix.compile.QueryOptimizerTest |
|   | phoenix.mapreduce.util.IndexColumnNamesTest |
|   | phoenix.mapreduce.util.PhoenixConfigurationUtilTest |
|   | phoenix.jdbc.PhoenixResultSetMetadataTest |
|   | phoenix.mapreduce.index.IndexScrutinyTableOutputTest |
|   | phoenix.util.csv.StringToArrayConverterTest |
|   | phoenix.compile.TenantSpecificViewIndexCompileTest |
|   | phoenix.compile.LimitCompilerTest |
|   | phoenix.compile.StatementHintsCompilationTest |
|   | phoenix.util.PhoenixRuntimeTest |
|   | phoenix.schema.RowKeyValueAccessorTest |
|   | phoenix.expression.RoundFloorCeilExpressionsTest |
|   | phoenix.index.PrepareIndexMutationsForRebuildTest |
|   | phoenix.hbase.index.covered.NonTxIndexBuilderTest |
|   | phoenix.jdbc.PhoenixPreparedStatementTest |
|   | phoenix.compile.HavingCompilerTest |
|   | phoenix.index.IndexMaintainerTest |
|   | phoenix.query.KeyRangeClipTest |
|   | phoenix.util.PhoenixEncodeDecodeTest |
|   | phoenix.compile.QueryCompilerTest |
|   | phoenix.compile.WhereOptimizerTest |
|   | phoenix.query.ScannerLeaseRenewalTest |
|   | phoenix.index.IndexScrutinyMapperTest |
|   | phoenix.util.csv.CsvUpsertExecutorTest |
|   | phoenix.schema.MetaDataClientTest |
|   | phoenix.iterate.AggregateResultScannerTest |
|   | phoenix.compile.CreateTableCompilerTest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux ef3b73854e0d 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 79c66fd |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/1/testReport/ |
| Max. process+thread count | 428 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 12s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m  6s |  master passed  |
| +0 |  hbaserecompile  |  24m  1s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 19s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 52s |  master passed  |
| +0 :ok: |  spotbugs  |   3m 16s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   9m 59s |  the patch passed  |
| +0 |  hbaserecompile  |  20m 31s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  5s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  5s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 17s |  phoenix-core: The patch generated 16 new + 3016 unchanged - 12 fixed = 3032 total (was 3028)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 51s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 38s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   1m 48s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 14s |  The patch does not generate ASF License warnings.  |
|  |   |  59m 31s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.schema.MutationTest |
|   | phoenix.compile.QueryOptimizerTest |
|   | phoenix.compile.QueryCompilerTest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 5e54e04c540e 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 79c66fd |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/2/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/2/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/2/testReport/ |
| Max. process+thread count | 424 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 19s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 12s |  master passed  |
| +0 |  hbaserecompile  |  22m  6s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 53s |  master passed  |
| +0 :ok: |  spotbugs  |   3m  7s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 10s |  the patch passed  |
| +0 |  hbaserecompile  |  18m 36s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  3s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 50s |  phoenix-core: The patch generated 24 new + 3016 unchanged - 13 fixed = 3040 total (was 3029)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 50s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 15s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  |   1m 36s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 16s |  The patch does not generate ASF License warnings.  |
|  |   |  59m 15s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.compile.QueryOptimizerTest |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux edf57c85ffd8 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / c9e05f0 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/3/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/3/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/3/testReport/ |
| Max. process+thread count | 464 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/3/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  1s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  16m 17s |  master passed  |
| +0 |  hbaserecompile  |  23m 22s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 37s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 56s |  master passed  |
| +0 :ok: |  spotbugs  |   3m 16s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 24s |  the patch passed  |
| +0 |  hbaserecompile  |  18m  9s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  3s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 35s |  phoenix-core: The patch generated 12 new + 3028 unchanged - 1 fixed = 3040 total (was 3029)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 50s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 23s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 102m  1s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 44s |  The patch does not generate ASF License warnings.  |
|  |   | 158m 24s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.monitoring.PhoenixLoggingMetricsIT |
|   | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/4/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 89cede565fca 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / c9e05f0 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/4/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/4/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/4/testReport/ |
| Max. process+thread count | 13745 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/4/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 12s |  master passed  |
| +0 |  hbaserecompile  |  22m 43s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  4s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 51s |  master passed  |
| +0 :ok: |  spotbugs  |   3m  1s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m 28s |  the patch passed  |
| +0 |  hbaserecompile  |  18m 15s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  2s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 34s |  phoenix-core: The patch generated 24 new + 3016 unchanged - 13 fixed = 3040 total (was 3029)  |
| +1 :green_heart: |  whitespace  |   0m  1s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 57s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 24s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 112m 17s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 42s |  The patch does not generate ASF License warnings.  |
|  |   | 168m 20s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |
|   | phoenix.end2end.PermissionNSEnabledIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/5/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 42f84d785271 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / c9e05f0 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/5/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/5/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/5/testReport/ |
| Max. process+thread count | 8123 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/5/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ankitsinghal** [comment]
having duplicate column names at different hierarchy is not fine? Like below table shouldn't be correct or not allowed?
`
CREATE TABLE multiple_columns_with_same_name(id integer primary key, id /*comment , it will be "0".id*/ integer, "cf1".id integer,"cf2".id integer);`

**Comment by stoty** [comment]
In your example, how would you address the pk id ?
What would / should  rs.getString("id") return ? 
To be consistent, it should be "0".id. However, that leaves no way to address pk.id.

This is the reason that specifically PK and the default cf should not have identical names.

**Comment by ankitsinghal** [comment]
```In your example, how would you address the pk id ?
What would / should rs.getString("id") return ?
To be consistent, it should be "0".id. However, that leaves no way to address pk.id.
This is the reason that specifically PK and the default cf should not have identical names.


```
yes, it makes sense, we can't force users to refer every default cf column with "0." and primary columns directly.

**Comment by virajjasani** [comment]
Thanks @ankitsinghal for taking a look. Btw somewhat related discussion happened on #1118 yesterday since I raised both master and backport PRs together. I agree that column with user specified CF should be allowed same column name as pk (or non-pk from different CF) but it's just that allowing the same in default CF makes it bit complicated.
Thanks

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m  1s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  17m 30s |  master passed  |
| +0 |  hbaserecompile  |  24m 58s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  6s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 16s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 55s |  master passed  |
| +0 :ok: |  spotbugs  |   3m 30s |  phoenix-core in master has 954 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  10m 11s |  the patch passed  |
| +0 |  hbaserecompile  |  20m 42s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 11s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 11s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 25s |  phoenix-core: The patch generated 12 new + 3027 unchanged - 1 fixed = 3039 total (was 3028)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   1m  1s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 52s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 112m 25s |  phoenix-core in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 15s |  The patch does not generate ASF License warnings.  |
|  |   | 171m 22s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/6/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 2712bd6e898f 4.15.0-126-generic #129-Ubuntu SMP Mon Nov 23 18:53:38 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 22f7d41 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/6/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/6/testReport/ |
| Max. process+thread count | 9959 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/6/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 29s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| +1 :green_heart: |  test4tests  |   0m  0s |  The patch appears to include 1 new or modified test files.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m 28s |  master passed  |
| +0 |  hbaserecompile  |  22m 58s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  2s |  master passed  |
| +1 :green_heart: |  checkstyle  |   1m 47s |  master passed  |
| +1 :green_heart: |  javadoc  |   0m 52s |  master passed  |
| +0 :ok: |  spotbugs  |   3m  8s |  phoenix-core in master has 959 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   8m  5s |  the patch passed  |
| +0 |  hbaserecompile  |  17m 45s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m  3s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  3s |  the patch passed  |
| -1 :x: |  checkstyle  |   1m 51s |  phoenix-core: The patch generated 24 new + 3015 unchanged - 13 fixed = 3039 total (was 3028)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 52s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 10s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 103m 50s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 37s |  The patch does not generate ASF License warnings.  |
|  |   | 164m 26s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |
|   | phoenix.end2end.PermissionNSDisabledWithCustomAccessControllerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/7/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1117 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux ef34a749f573 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 9e90779 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/7/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/7/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/7/testReport/ |
| Max. process+thread count | 14316 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1117/7/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request merged**
