### PR TITLE
PHOENIX-6435 Fix test flapper ImmutableIndexIT, PermissionNSDisabledW…

### PR DESCRIPTION
**Pull request by yanxinyi**
…ithCustomAccessControllerIT and PermissionNSEnabledWithCustomAccessControllerIT

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 58s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  14m 51s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m  8s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 27s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 51s |  4.x passed  |
| +0 :ok: |  spotbugs  |   3m 25s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m 50s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  7s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  7s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 28s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 34s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 210m 13s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 41s |  The patch does not generate ASF License warnings.  |
|  |   | 252m 58s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.index.PartialIndexRebuilderIT |
|   | phoenix.end2end.BackwardCompatibilityIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1195 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 3a47717d5564 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 33f2463 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/1/testReport/ |
| Max. process+thread count | 5034 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by jpisaac — APPROVED** [review]
LGTM +1

**Comment by stoty** [comment]
AFAICT this only has an effect on ViewTTLIT.

The other tests are already run in their own cluster, as they inherit the category from  their parents, so the changes are merely cosmetic there.

**Comment by virajjasani** [comment]
Agree, `BasePermissionsIT` and other parent tests are already of Category: `NeedsOwnMiniClusterTest`

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   7m  6s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  15m  1s |  4.x passed  |
| +1 :green_heart: |  compile  |   1m  8s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 27s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 48s |  4.x passed  |
| +0 :ok: |  spotbugs  |   3m 17s |  phoenix-core in 4.x has 945 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   6m 48s |  the patch passed  |
| +1 :green_heart: |  compile  |   1m  6s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m  6s |  the patch passed  |
| +1 :green_heart: |  checkstyle  |   0m 27s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 49s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m 30s |  the patch passed  |
||| _ Other Tests _ |
| +1 :green_heart: |  unit  | 206m  0s |  phoenix-core in the patch passed.  |
| +1 :green_heart: |  asflicense  |   0m 10s |  The patch does not generate ASF License warnings.  |
|  |   | 247m 30s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1195 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 59618f2a35de 4.15.0-128-generic #131-Ubuntu SMP Wed Dec 9 06:57:35 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / b0772eb |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/2/testReport/ |
| Max. process+thread count | 5239 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1195/2/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
Were you able to find the specific interference with other tests in ViewTTLIT that running it in its own cluster fixes ?
We were able to fix similar tests by making the checks in the SYSTEM tables more specific, so that other tests do not trip them.

**Comment by yanxinyi** [comment]
> Were you able to find the specific interference with other tests in ViewTTLIT that running it in its own cluster fixes ?
> We were able to fix similar tests by making the checks in the SYSTEM tables more specific, so that other tests do not trip them.

No. I was not able to reproduce it on my machine. I also checked a list of CI builds, none of them have ViewTTLIT failures. Our internal CI ViewTTLIT failure log aged out, but we fixed it by running it in its own cluster.

https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/4.x/test_results_analyzer/
https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/4.16/test_results_analyzer/
https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-mulitbranch/job/master/test_results_analyzer/

**Pull request merged**
