### PR TITLE
Exclude libraries with CVEs from phoenix-client-embedded

### PR DESCRIPTION
**Pull request by kokosing**

### CODE REVIEW

**Comment by kokosing** [comment]
FYI @stoty @virajjasani

**Comment by stoty** [comment]
I have opened a [DISCUSS] thread on dev@p.a.o. on how to handle transitive dependecy CVEs.
Please join the discussion.

**Comment by virajjasani** [comment]
Do we know if CVEs of both of these dependencies have been resolved with some recently released version of Hadoop?

**Comment by stoty** [comment]
I have added dependencyManagement for these in a different commit.

**Pull request closed without merging**
