### PR TITLE
PHOENIX-6114 Create shaded phoenix-pherf and remove lib dir from asse…

### PR DESCRIPTION
**Pull request by stoty**
…mbly

remove pherf-cluster.py
remove phoenix-pherf-minimal shaded jar
remove /lib dir from assembly
remove /dev library from assemby
shade phoenix-pherf instead
move phoenix-pherf.jar to root
update scripts for new jar names and paths

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 32s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 58s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  13m 38s |  master passed  |
| +0 |  hbaserecompile  |  27m 13s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 57s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 29s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| -1 :x: |  mvninstall  |  10m 57s |  root in the patch failed.  |
| +0 |  hbaserecompile  |  19m 50s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m 21s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 21s |  the patch passed  |
| +1 :green_heart: |  pylint  |   0m  7s |  The patch generated 0 new + 87 unchanged - 31 fixed = 87 total (was 118)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  6s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 129m 17s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m  2s |  The patch generated 612 ASF License warnings.  |
|  |   | 188m 33s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1131 |
| Optional Tests | dupname asflicense pylint xml javac javadoc unit compile |
| uname | Linux b1df78f3e909 4.15.0-60-generic #67-Ubuntu SMP Thu Aug 22 16:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / d2be16d |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 13574 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf phoenix-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/2/console |
| versions | git=2.7.4 maven=3.3.9 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by yanxinyi** [comment]
My local build and I precommit build failed because of the same reason. This is only for the master branch but not 4.x

./patch-mvninstall-root.txt:[ERROR] Failed to execute goal org.apache.maven.plugins:maven-install-plugin:2.5.2:install-file (default-install) on project phoenix-pherf: The specified file '/home/jenkins/jenkins-home/workspace/enix-PreCommit-GitHub-PR_PR-1131/yetus-general-check/src/phoenix-pherf/target/phoenix-pherf-5.1.0-SNAPSHOT-minimal.jar' not exists -> [Help 1]

**Comment by yanxinyi** [comment]
Ok. I guess you probably forgot to remove this 
https://github.com/apache/phoenix/blob/master/phoenix-pherf/pom.xml#L299

**Comment by stoty** [comment]
Thank you @yanxinyi .
Yes. I've fixed that on the 4.x PR, but not here.
Pushed the fix now.

**Review by yanxinyi — APPROVED** [review]
+1 LGTM

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   5m 42s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 55s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  15m 19s |  master passed  |
| +0 |  hbaserecompile  |  28m 51s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m  2s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m 34s |  master passed  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 15s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |  11m 52s |  the patch passed  |
| +0 |  hbaserecompile  |  20m 29s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m  9s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m  9s |  the patch passed  |
| +1 :green_heart: |  pylint  |   0m  9s |  The patch generated 0 new + 87 unchanged - 31 fixed = 87 total (was 118)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  7s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m 13s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 104m 21s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   2m 24s |  The patch generated 612 ASF License warnings.  |
|  |   | 174m 36s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1131 |
| Optional Tests | dupname asflicense pylint xml javac javadoc unit compile |
| uname | Linux 3492faedc572 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / d2be16d |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/3/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/3/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/3/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 13390 (vs. ulimit of 30000) |
| modules | C: phoenix-pherf phoenix-assembly . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1131/3/console |
| versions | git=2.7.4 maven=3.3.9 pylint=2.4.4 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Pull request closed without merging**
