### PR TITLE
PHOENIX-4668: Remove unnecessary table descriptor modification for SPLIT_POLICY column

### PR DESCRIPTION
**Pull request by ChinmaySKulkarni**
Removed the code which: removed the SPLIT_POLICY in the system catalog
table descriptor and then added it and modified the table.
This was earlier done as a workaround for HBASE-12570.
We specifically add the SPLIT_POLICY when creating system tables already
as part of the patch for PHOENIX-1674, hence this is no longer required.

### CODE REVIEW

**Comment by ChinmaySKulkarni** [comment]
@twdsilva @JamesRTaylor please review. Thanks.

**Comment by twdsilva** [comment]
+1

**Comment by ChinmaySKulkarni** [comment]
@JamesRTaylor please review. Thanks!

**Comment by JamesRTaylor** [comment]
+1. Will commit soon.

**Pull request closed without merging**
