### PR TITLE
PHOENIX-6346 Javadoc generation fails with Java 8

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Review by joshelser — APPROVED** [review]
Looks fine!

Related, is there an option on maven-javadoc-plugin that would be "less strict" to not require this in the future?

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 17s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  2s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +0 :ok: |  mvndep  |   4m 29s |  Maven dependency ordering for branch  |
| +1 :green_heart: |  mvninstall  |  10m 59s |  master passed  |
| +0 |  hbaserecompile  |  21m 57s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 34s |  master passed  |
| +1 :green_heart: |  checkstyle  |   9m 23s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 12s |  master passed  |
| +0 :ok: |  spotbugs  |   3m  0s |  phoenix-core in master has 954 extant spotbugs warnings.  |
| +0 :ok: |  spotbugs  |   0m 51s |  phoenix-pherf in master has 42 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +0 :ok: |  mvndep  |   0m 12s |  Maven dependency ordering for patch  |
| +1 :green_heart: |  mvninstall  |   8m 13s |  the patch passed  |
| +0 |  hbaserecompile  |  14m 38s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 35s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 35s |  the patch passed  |
| -1 :x: |  checkstyle  |   9m  5s |  phoenix-core: The patch generated 232 new + 19549 unchanged - 256 fixed = 19781 total (was 19805)  |
| -1 :x: |  checkstyle  |   0m 25s |  phoenix-pherf: The patch generated 6 new + 312 unchanged - 6 fixed = 318 total (was 318)  |
| -1 :x: |  whitespace  |   0m  0s |  The patch has 18 line(s) that end in whitespace. Use git apply --whitespace=fix <<patch_file>>. Refer https://git-scm.com/docs/git-apply  |
| -1 :x: |  whitespace  |   0m  0s |  The patch 1 line(s) with tabs.  |
| -1 :x: |  javadoc  |   0m 50s |  phoenix-core generated 30 new + 66 unchanged - 34 fixed = 96 total (was 100)  |
| +1 :green_heart: |  spotbugs  |   4m 12s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 101m 28s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  unit  |  10m  0s |  phoenix-pherf in the patch passed.  |
| +1 :green_heart: |  asflicense  |   1m 19s |  The patch does not generate ASF License warnings.  |
|  |   | 190m  8s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.PermissionNSEnabledWithCustomAccessControllerIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1120 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaserebuild hbaseanti checkstyle compile |
| uname | Linux 5713a77d5fbb 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / c9e05f0 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/diff-checkstyle-phoenix-pherf.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/whitespace-eol.txt |
| whitespace | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/whitespace-tabs.txt |
| javadoc | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/diff-javadoc-javadoc-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/testReport/ |
| Max. process+thread count | 14119 (vs. ulimit of 30000) |
| modules | C: phoenix-core phoenix-pherf U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1120/1/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
Thanks @joshelser 

I think that fixing up Javadocs would be the better option long term.
I dared not check what the generated Javadocs pages look like.

**Comment by joshelser** [comment]
> I think that fixing up Javadocs would be the better option long term. I dared not check what the generated Javadocs pages look like.

Heh. Yes, I agree with you that's the right path long term. Just wanted to acknowledge that this would be a massive undertaking that everyone would need to contribute to :)

**Pull request closed without merging**
