### PR TITLE
PHOENIX-5268 HBase 2.1/2.2 compatibility

### PR DESCRIPTION
**Pull request by stoty**
depend on Hbase 2.2.1
adopt code to the changed HBase APIs
update the maven version
synchronize @AfterClass and @BeforeClass in ParallelStatsDisabledIT

Co-authored-by: Ankit Singhal <ankitsinghal59@gmail.com

### CODE REVIEW

**Comment by joshelser** [comment]
I see some test failures in org.apache.phoenix.end2end.LastValueFunctionIT and org.apache.phoenix.end2end.NullIT. Will have to re-run against `master` to make sure these aren't just flaky.

**Comment by stoty** [comment]
> I see some test failures in org.apache.phoenix.end2end.LastValueFunctionIT and org.apache.phoenix.end2end.NullIT. Will have to re-run against `master` to make sure these aren't just flaky.

FWIW, I don't remember seeing either of those those fail during my testing.

**Comment by joshelser** [comment]
Ah, they just OOM'ed because the number of forked ITs was too large :). False alarm!

**Comment by mlkui** [comment]
Phoenix 5.0.0 has not been updated for one year( since 04/jul/2018)...
When HBase 2.2.2 will be supported after all?

**Comment by joshelser** [comment]
@mlkui a random pull request is the wrong place to ask about project roadmap. These discussions happen on the dev mailing list.

**Comment by z-york** [comment]
@joshelser @stoty What is blocking this PR? Happy to help if I can.

**Comment by stoty** [comment]
Apart from needing an update it to HBase 2.2.2, I consider the patch production ready.
The project hasn't made a decision yet on how to handle the loss of HBase 2.0 compatibility ( abandon it, fork the codebase, or use some kind of compat module/maven profile hack)
It is probably not a bad time to (re)start that discussion.

**Comment by stoty** [comment]
Updated for Hbase 2.2.1 and current Phoenix master

**Comment by z-york** [comment]
@stoty I was trying to test your PR out (rebased on 5.0.0-HBase-2.0) and I'm hitting this error:
phoenix-core/src/main/java/org/apache/phoenix/hbase/index/covered/data/IndexMemStore.java:[84,20] compare(org.apache.hadoop.hbase.Cell,org.apache.hadoop.hbase.Cell) in <anonymous org.apache.phoenix.hbase.index.covered.data.IndexMemStore$1> cannot override compare(org.apache.hadoop.hbase.Cell,org.apache.hadoop.hbase.Cell) in org.apache.hadoop.hbase.CellComparatorImpl

However, I'm sure this has been fixed somehow (even though I can't seem to figure out how since it looks like it is still trying to override the method on the master branch: https://github.com/apache/phoenix/blob/master/phoenix-core/src/main/java/org/apache/phoenix/hbase/index/covered/data/IndexMemStore.java#L82)

Did you run into that error?

**Comment by joshelser** [comment]
Lars/Andrew -- what's your feeling: should we get this compile-time compatibility committed while Istvan iterates on runtime compatibility? Seems like a good idea to me.

**Comment by stoty** [comment]
This is the non-modular version, I just mixed up the PRs in the ticket originally, and the bad PR link got sent to the list. The link is fixed in the ticket now. Sorry for the confusion.

**Comment by joshelser** [comment]
That makes more sense :)

**Comment by stoty** [comment]
Closing this, as the #687 is the preferred solution.

**Pull request closed without merging**
