### PR TITLE
PHOENIX-6551 Bump HBase version to 2.4.6 and 2.2.7

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   8m 21s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  30m 28s |  master passed  |
| +0 |  hbaserecompile  |  39m 38s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m 35s |  master passed  |
| +1 :green_heart: |  javadoc  |   2m  1s |  master passed  |
||| _ Patch Compile Tests _ |
| -1 :x: |  mvninstall  |   0m 46s |  root in the patch failed.  |
| +0 |  hbaserecompile  |  55m 45s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m 27s |  the patch passed  |
| +1 :green_heart: |  javac  |   2m 27s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   2m  3s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 247m 26s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m  9s |  The patch generated 612 ASF License warnings.  |
|  |   | 319m 56s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1313 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux f05dbdbc355d 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / 8fb38e4 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| mvninstall | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/artifact/yetus-general-check/output/patch-mvninstall-root.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 6862 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/1/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by virajjasani** [comment]
Looks like some issue resolving artifacts, let me recheck repositories content and retrigger the build if everything is fine:

The following artifacts could not be resolved: org.apache.hbase:hbase-common:jar:2.4.6, org.apache.hbase:hbase-mapreduce:jar:2.4.6, org.apache.hbase:hbase-metrics-api:jar:2.4.6, org.apache.hbase:hbase-metrics:jar:2.4.6, org.apache.hbase:hbase-protocol:jar:2.4.6, org.apache.hbase:hbase-protocol-shaded:jar:2.4.6, org.apache.hbase:hbase-client:jar:2.4.6, org.apache.hbase:hbase-server:jar:2.4.6, org.apache.hbase:hbase-hadoop-compat:jar:2.4.6, org.apache.hbase:hbase-hadoop2-compat:jar:2.4.6, org.apache.hbase:hbase-zookeeper:jar:2.4.6, org.apache.hbase:hbase-it:jar:tests:2.4.6, org.apache.hbase:hbase-common:jar:tests:2.4.6, org.apache.hbase:hbase-server:jar:tests:2.4.6, org.apache.hbase:hbase-testing-util:jar:2.4.6, org.apache.hbase:hbase-endpoint:jar:2.4.6: Could not find artifact org.apache.hbase:hbase-common:jar:2.4.6 in apache release (https://repository.apache.org/content/repositories/releases/) -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException

**Comment by stoty** [comment]
Interesting.
The CI checks recompile hbase from the officially released source to get around the Hadoop3 issue, and so did I in my local tests.
It seems that the 2.4.6 release process isn't properly done, and the artifacts weren't pulished to maven.
We should probably wait until that is resolved. (and notify the HBase project)

**Comment by stoty** [comment]
@apurtell Do you know the reason ?

**Comment by virajjasani** [comment]
@stoty It's resolved now, just triggered the QA run.

**Comment by stoty** [comment]
I still cannot see 2.4.6 on https://repo.maven.apache.org/maven2/org/apache/hbase/hbase-client/
(though it may just take some time to catch up)

**Comment by virajjasani** [comment]
> I still cannot see 2.4.6 on https://repo.maven.apache.org/maven2/org/apache/hbase/hbase-client/
> (though it may just take some time to catch up)

Yeah it should show up after some time. It's present here in r.a.o though https://repository.apache.org/content/repositories/releases/org/apache/hbase/hbase-client/2.4.6/

**Comment by stoty** [comment]
It has appeared. Thanks for your intervention.
However, we do not use the public hbase maven artifacts anywhere in the CI pipeline for 5.x, so it shouldn't make a difference for the CI run.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   1m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ master Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  25m  1s |  master passed  |
| +0 |  hbaserecompile  |  32m 46s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   2m  0s |  master passed  |
| +1 :green_heart: |  javadoc  |   1m 27s |  master passed  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  18m 38s |  the patch passed  |
| +0 |  hbaserecompile  |  62m 39s |  HBase recompiled.  |
| +1 :green_heart: |  compile  |   1m 52s |  the patch passed  |
| +1 :green_heart: |  javac  |   1m 52s |  the patch passed  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  xml  |   0m  2s |  The patch has no ill-formed XML file.  |
| +1 :green_heart: |  javadoc  |   1m 18s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 126m 26s |  root in the patch failed.  |
| -1 :x: |  asflicense  |   1m  6s |  The patch generated 612 ASF License warnings.  |
|  |   | 197m  3s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1313 |
| Optional Tests | dupname asflicense javac javadoc unit xml compile |
| uname | Linux ae52bababa32 4.15.0-143-generic #147-Ubuntu SMP Wed Apr 14 16:10:11 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / f606289 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/2/artifact/yetus-general-check/output/patch-unit-root.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/2/testReport/ |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 11365 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1313/2/console |
| versions | git=2.7.4 maven=3.3.9 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by virajjasani — APPROVED** [review]
+1, thank you @stoty

**Pull request closed without merging**
