### PR TITLE
PHOENIX-6705 PagedRegionScanner#next throws NPE if pagedFilter is not initialized.

### PR DESCRIPTION
**Pull request by shahrs87**

### CODE REVIEW

**Comment by shahrs87** [comment]
Ping @kadirozde  @gokceni  @gjacoby126  for review on this small PR. Thank you.

**Comment by stoty** [comment]
+1 LGTM

**Review by stoty — APPROVED** [review]

**Comment by shahrs87** [comment]
@stoty  Can you please help me find out why the patch in `phoenix-core` failed ? The link is not working.
Also this patch applies cleanly to `4.x` and `4.16` branch. If everything looks good to you, can you please merge the changes. Thank you.

**Review by chrajeshbabu — APPROVED** [review]

**Comment by kadirozde** [comment]
+1 Thanks

**Review by gjacoby126 — APPROVED** [review]
+1

**Comment by gjacoby126** [comment]
@shahrs87 - the consensus on the Phoenix dev list seems to be that 4.16 / 4.x will be deprecated, so for now I don't think there's a need for a backport since there are no planned releases.

**Pull request merged**
