### PR TITLE
PHOENIX-7157 Upgrade to phoenix-thirdparty 2.1.0

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by stoty** [comment]
The test results have aged out.
I have kicked off another CI run.

**Comment by NihalJain** [comment]
Ping @chrajeshbabu, @stoty, @virajjasani

**Review by stoty — APPROVED** [review]
1 LGTM

**Review by virajjasani — APPROVED** [review]

**Comment by virajjasani** [comment]
Shall we run one round of build?

**Comment by virajjasani** [comment]
We are good, latest build results are not that old: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1771/6/

**Pull request merged**
