### PR TITLE
PHOENIX-7157 Upgrade to phoenix-thirdparty 2.1.0

### PR DESCRIPTION
**Pull request by NihalJain**

### CODE REVIEW

**Comment by NihalJain** [comment]
This is a backport of https://github.com/apache/phoenix/pull/1771.
Created this to let jenkins build/test the change and ensure no error.

**Comment by NihalJain** [comment]
No build happened for this, need to check

**Comment by NihalJain** [comment]
Seems build had passed in Jenkins, but result was not sent back to github somehow. See https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1772/1/consoleFull
```
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47                            Adding GitHub Statuses
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47  
18:50:47  
18:50:47  ERROR: Failed to write github status. Token expired or missing repo:status write?
18:50:47  
18:50:47  
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47                     Writing HTML to /precommit/report.htm
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47  
18:50:47  
18:50:47  
18:50:47  
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47                            Adding comment to JIRA
18:50:47  ============================================================================
18:50:47  ============================================================================
18:50:47  
18:50:47  
18:50:47  JIRA Plugin: no credentials provided to write a comment.
18:50:48  
18:50:48  
18:50:48  -1 overall
18:50:48  
18:50:48  | Vote |          Subsystem |  Runtime   | Comment
18:50:48  ============================================================================
18:50:48  |   0  |            reexec  |   0m 32s   | Docker mode activated. 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |      |                    |            | Prechecks 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |  +1  |           dupname  |   0m  1s   | No case conflicting files found. 
18:50:48  |  +1  |           @author  |   0m  0s   | The patch does not contain any 
18:50:48  |      |                    |            | @author tags.
18:50:48  |  -1  |        test4tests  |   0m  0s   | The patch doesn't appear to include 
18:50:48  |      |                    |            | any new or modified tests. Please
18:50:48  |      |                    |            | justify why no new tests are needed
18:50:48  |      |                    |            | for this patch. Also please list what
18:50:48  |      |                    |            | manual steps were performed to verify
18:50:48  |      |                    |            | this patch.
18:50:48  +---------------------------------------------------------------------------
18:50:48  |      |                    |            | 5.1 Compile Tests 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |  +1  |        mvninstall  |   9m  7s   | 5.1 passed 
18:50:48  |  +0  |    hbaserecompile  |  10m  2s   | HBase recompiled. 
18:50:48  |  +1  |           compile  |   1m  6s   | 5.1 passed 
18:50:48  |  +1  |           javadoc  |   1m 27s   | 5.1 passed 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |      |                    |            | Patch Compile Tests 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |  +1  |        mvninstall  |   1m 19s   | the patch passed 
18:50:48  |  +1  |         codespell  |   0m 11s   | No new issues. 
18:50:48  |  +1  |           compile  |   1m  0s   | the patch passed 
18:50:48  |  +1  |             javac  |   1m  0s   | the patch passed 
18:50:48  |  +1  |            blanks  |   0m  0s   | The patch has no blanks issues. 
18:50:48  |  +1  |               xml  |   0m  1s   | The patch has no ill-formed XML 
18:50:48  |      |                    |            | file.
18:50:48  |  +1  |           javadoc  |   1m 25s   | the patch passed 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |      |                    |            | Other Tests 
18:50:48  +---------------------------------------------------------------------------
18:50:48  |  +1  |              unit  | 106m 13s   | root in the patch passed. 
18:50:48  |  +1  |        asflicense  |   0m 41s   | The patch does not generate ASF 
18:50:48  |      |                    |            | License warnings.
18:50:48  |      |                    | 135m 18s   |
```
Retriggered build.

**Comment by NihalJain** [comment]
Ping @chrajeshbabu, @stoty, @virajjasani

**Comment by chrajeshbabu** [comment]
+1 lgtm

**Pull request merged**
