### PR TITLE
PHOENIX-7369 Avoid redundant recursive getTable() RPC calls

### PR DESCRIPTION
**Pull request by virajjasani**
Jira: PHOENIX-7369

### CODE REVIEW

**Comment by virajjasani** [comment]
@stoty i see that all builds are going to https://ci-hadoop.apache.org/computer/hadoop1/ and the host does not seem healthy as all builds get aborted. What can we do? Can we disconnect the host using jenkins ui? Or shall i inform ASF Infra reg this by creating INFRA Jira?

**Review by kadirozde — APPROVED** [review]

**Comment by stoty** [comment]
Yes, the pre-yetus scripts did list and exclude single CI hosts explictily, so that is possible (or at least it was possible at the time).

However, I think that asking for help from INFRA is the way to go, and we should only resort to excluding hosts if infra cannot help with the problem.

**Comment by virajjasani** [comment]
created Jira [INFRA-25995](https://issues.apache.org/jira/browse/INFRA-25995)

**Comment by virajjasani** [comment]
Marked Hadoop1 node offline as per recommendation on ASF slack channel asfinfra, now the build is progressing: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1944/

**Pull request merged**
