### PR TITLE
PHOENIX-6371 : Script to verify release candidate

### PR DESCRIPTION
**Pull request by virajjasani**
Script that can download RC locally, extract tar and verify:

- Signture
- Checksum
- Rat check
- Build
- Unit tests

### CODE REVIEW

**Comment by virajjasani** [comment]
Tested successfully against current RCs 5.1.0RC4 and 4.16.0RC2.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   4m 14s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 |  hbaserecompile  |   6m 48s |  HBase recompiled.  |
||| _ Patch Compile Tests _ |
| +0 |  hbaserecompile  |   6m 27s |  HBase recompiled.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| -1 :x: |  shelldocs  |   0m  4s |  The patch generated 22 new + 54 unchanged - 0 fixed = 76 total (was 54)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 26s |  The patch generated 611 ASF License warnings.  |
|  |   |  18m 44s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/1/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1134 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 281825f0f26e 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / d6672f4 |
| shelldocs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/1/artifact/yetus-general-check/output/diff-patch-shelldocs.txt |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/1/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 76 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/1/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 27s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 |  hbaserecompile  |   6m 43s |  HBase recompiled.  |
||| _ Patch Compile Tests _ |
| +0 |  hbaserecompile  |   6m 29s |  HBase recompiled.  |
| +1 :green_heart: |  shellcheck  |   0m  1s |  There were no new shellcheck issues.  |
| -1 :x: |  shelldocs  |   0m  2s |  The patch generated 22 new + 54 unchanged - 0 fixed = 76 total (was 54)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 25s |  The patch generated 611 ASF License warnings.  |
|  |   |  14m 53s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/2/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1134 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 043187c3e6d0 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / d6672f4 |
| shelldocs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/2/artifact/yetus-general-check/output/diff-patch-shelldocs.txt |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/2/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 96 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/2/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 28s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
||| _ master Compile Tests _ |
| +0 |  hbaserecompile  |   6m 50s |  HBase recompiled.  |
||| _ Patch Compile Tests _ |
| +0 |  hbaserecompile  |   6m 24s |  HBase recompiled.  |
| +1 :green_heart: |  shellcheck  |   0m  0s |  There were no new shellcheck issues.  |
| -1 :x: |  shelldocs  |   0m  2s |  The patch generated 22 new + 54 unchanged - 0 fixed = 76 total (was 54)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
||| _ Other Tests _ |
| -1 :x: |  asflicense  |   0m 25s |  The patch generated 611 ASF License warnings.  |
|  |   |  14m 57s |   |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/3/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1134 |
| Optional Tests | dupname asflicense shellcheck shelldocs |
| uname | Linux 55eb753d0b66 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | master / d6672f4 |
| shelldocs | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/3/artifact/yetus-general-check/output/diff-patch-shelldocs.txt |
| asflicense | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/3/artifact/yetus-general-check/output/patch-asflicense-problems.txt |
| Max. process+thread count | 91 (vs. ulimit of 30000) |
| modules | C: . U: . |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1134/3/console |
| versions | git=2.7.4 maven=3.3.9 shellcheck=0.7.0 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Review by gjacoby126 — APPROVED** [review]
+1, looks really useful

**Comment by virajjasani** [comment]
Thanks @gjacoby126 , i just used it for voting of both ongoing RCs.

**Pull request merged**
