### PR TITLE
PHOENIX-3603 Fix compilation errors against hbase 1.3.0 release

### PR DESCRIPTION
**Pull request by z-york**

### CODE REVIEW

**Comment by apurtell** [comment]
lgtm

Have you tried running the Phoenix test suite with these changes in place @z-york  ?

**Comment by z-york** [comment]
I tried running the tests. I got most of the way done with two (seemingly unrelated failures), but it seemed to be hanging (or running a VERY long test >1hour with no progress) so I killed it. 

I then tried running on an ec2 instance (to offload the work from my local machine) and had this failure:
testMultipleConnectionsAsSameUserWithoutLogin(org.apache.phoenix.jdbc.SecureUserConnectionsTest)  Time elapsed: 0.13 sec  <<< ERROR!
  java.lang.RuntimeException: Couldn't get the current user!!
          at org.apache.phoenix.jdbc.SecureUserConnectionsTest.testMultipleConnectionsAsSameUserWithoutLogin(SecureUserConnectionsTest.java:354)

Am I doing something wrong on the ec2 instance?
Thanks!

**Comment by z-york** [comment]
Just trying to run the phoenix-core tests (since that was the only place I changed), I get stuck at this line indefinitely:

  Tests run: 19, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 86.487 sec - in org.apache.phoenix.tx.TransactionIT
  Tests run: 20, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 110.872 sec - in org.apache.phoenix.tx.TxCheckpointIT
  Tests run: 152, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 862.282 sec - in org.apache.phoenix.end2end.index.IndexIT
  Tests run: 1, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 302.238 sec <<< FAILURE! - in org.apache.phoenix.end2end.ServerExceptionIT
  testServerExceptionBackToClient(org.apache.phoenix.end2end.ServerExceptionIT)  Time elapsed: 302.237 sec  <<< FAILURE!
  java.lang.AssertionError
          at org.apache.phoenix.end2end.ServerExceptionIT.testServerExceptionBackToClient(ServerExceptionIT.java:63)

  Tests run: 26, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 357.293 sec <<< FAILURE! - in org.apache.phoenix.end2end.ArithmeticQueryIT
  testDecimalUpsertSelect(org.apache.phoenix.end2end.ArithmeticQueryIT)  Time elapsed: 304.524 sec  <<< FAILURE!
  java.lang.AssertionError: expected:<206> but was:<6000>
          at org.apache.phoenix.end2end.ArithmeticQueryIT.testDecimalUpsertSelect(ArithmeticQueryIT.java:236)

  Tests run: 40, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1,478.385 sec - in org.apache.phoenix.end2end.index.MutableIndexIT

**Comment by z-york** [comment]
Are PR's not automatically tested here as they are in other projects? @apurtell

**Comment by apurtell** [comment]
Phoenix development is hosted at the Apache foundation and primarily uses JIRA at https://issues.apache.org/jira/browse/PHOENIX for issue tracking and the mailing list dev@phoenix.apache.org (see http://apache.org/foundation/mailinglists.html). You will want to inquire there. I don't think Phoenix is officially supporting 1.3 yet, the master branch compiles against 1.2. The test failures you see may happen with or without your patch applied. Have you checked? Any or all of these issues are best brought up on dev@phoenix.

**Comment by z-york** [comment]
I tried to leave this on the JIRA, but it appears to be having problems right now:

@apurtell @JamesRTaylor  I think this PR should be enough to create a branch off of and then I can create follow up JIRAs to fix the test failures (which btw only happen with HBase 1.3.0).

The errors appear to all be timeouts. After spending a long time in the debugger, it looks like this appears to be the issue:
2017-01-31 15:52:50,292 INFO  [hconnection-0x629075f4-metaLookup-shared--pool13-t8] org.apache.hadoop.hbase.client.RpcRetryingCaller(147): Call exception, tries=19, retries=35, started=293834 ms ago, cancelled=false, msg=Connection refused row 'SYSTEM.CATALOG,T000001,99999999999999' on table 'hbase:meta' at region=hbase:meta,,1.1588230740, hostname=localhost,53669,1485852215660, seqNum=0

I will try to ask the dev list in the meantime.

**Comment by z-york** [comment]
@apurtell I figured out the testing issue (turns out it was a real issue with HBase not honoring DoNotRetryIOExceptions). I will be opening an issue today to fix that. Can we get this pushed to a hbase-1.3 branch? However, this part (scans that throw exceptions) will be broken with 1.3.0. However I heard talk of releasing a hbase-1.3.1 soon.

**Comment by apurtell** [comment]
Thanks @z-york . I plan to commit HBASE-17587 if tests pass there

**Comment by JamesRTaylor** [comment]
FYI, @z-york - @chrajeshbabu plans to create a 4.x-HBase-1.3 branch to house your changes. Thanks so much for pursuing this. We should be able to make a 4.10 release that supports HBase 1.3.

**Comment by apurtell** [comment]
We committed HBASE-17587

**Comment by stoty** [comment]
Already merged.

**Pull request closed without merging**
