### PR TITLE
PHOENIX-7427 PHOENIX-7418 breaks backwards compatibility tests

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
There is no universal java.security.value that works with all Java versions, so we run a dummy command, and only add the property if it doesn't cause errors.

On the JVM versions where the allow value is not accepted, it is not needed either.

**Comment by stoty** [comment]
Yetus does not run the affected tests.
See #2010 for the actual test results.

**Comment by stoty** [comment]
As seen on #2010, this does fix the BackwardCompatibility failures.

**Review by virajjasani — APPROVED** [review]
+1

**Pull request merged**
