### PR TITLE
PHOENIX-7181 Do not declare commons-configuration2 dependency

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
This runs the UTs fine with both HBase 2.5 and 2.4.

I have also tested this with Hadoop 3.2.5-SNAPSHOT. The UTs ran, and maven dependency:tree shows that it picks up the new commons-configuration2 version from Hadoop.

**Review by gjacoby126 — APPROVED** [review]
+1, assuming that asflicense failure is from something else. (Don't see how this patch could be causing one)

**Comment by stoty** [comment]
Thank you.
The Asflicence check often gives false positives, as it sometimes finds and flags generated files.
We could probably improve that test in Yetus. (Or maybe a Yetus upgrade would solve that problem)

**Comment by stoty** [comment]
merged manually

**Pull request closed without merging**
