### PR TITLE
PHOENIX-6601 Fix IndexTools bugs with namespace mapping

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by gjacoby126** [comment]
@stoty - code looks fine, but it looks like there's a build error in IndexBuildTimestampIT

**Comment by ss77892** [comment]
The way how the problem was addressed LGTM. As for the tests. There are a number of tests that are using IndexToolIT directly (usually runIndexTool method). Only one of those (IndexBuildTimestampIT) is calling setup for some purposes and that caused the compilation failure, but we might expect that others can be affected in some way as well. Not related to this particular patch, but some cleanup with the index-related IT tests needs to be done sometimes.

**Comment by stoty** [comment]
Sorry for the build error, I was too focused on IndexToolIT.java.
I've fixed the build now.

A lot of tests need cleanup, unfortunately.
We still have a lot of flakey tests as well.

**Review by gjacoby126 — APPROVED** [review]
+1 assuming the test run is clean. Thanks @stoty

**Comment by stoty** [comment]
ASF Jenkins is down.
Gonna run an off-line mvn verify check.

**Comment by stoty** [comment]
Offline test has completed successfully (well, actually it failed on a known flakey test, but that's expected)

**Pull request closed without merging**
