### PR TITLE
PHOENIX-6256: Fix MaxConcurrentConnectionsIT test flapper

### PR DESCRIPTION
**Pull request by ChinmaySKulkarni**

### CODE REVIEW

**Comment by ChinmaySKulkarni** [comment]
Please review @dbwong @yanxinyi

**Comment by dbwong** [comment]
Looks okay to me.  Testing approach for confirmation of no more flapping was?

**Review by dbwong — APPROVED** [review]

**Comment by ChinmaySKulkarni** [comment]
@dbwong Local debugging really. Let the TaskRO thread open a connection and made it wait and not close. So when the MaxCCIT test ended, that global connection was still open, causing the flapper.
With this change, the TaskRO never gets scheduled at all due to the initial wait being set to Long.MAX_VALUE

**Comment by virajjasani** [comment]
> TaskRO never gets scheduled at all due to the initial wait being set to Long.MAX_VALUE

In that case, only `TASK_HANDLING_INITIAL_DELAY_MS_ATTRIB` is sufficient since it is init delay so that first Scan never happens?

**Comment by ChinmaySKulkarni** [comment]
@virajjasani true, I just copied this setting from other tests where we wanted to disable SYS.TASK scans. I think it makes it more obvious that we are disabling the scans if we set both (for readability purposes)

Btw, my build aborted twice for some reason, so going to rebase and trigger another build

**Review by gjacoby126 — APPROVED** [review]
+1

**Comment by stoty** [comment]
:broken_heart: **-1 overall**






| Vote | Subsystem | Runtime | Comment |
|:----:|----------:|--------:|:--------|
| +0 :ok: |  reexec  |   0m 30s |  Docker mode activated.  |
||| _ Prechecks _ |
| +1 :green_heart: |  dupname  |   0m  0s |  No case conflicting files found.  |
| +1 :green_heart: |  hbaseanti  |   0m  0s |  Patch does not have any anti-patterns.  |
| +1 :green_heart: |  @author  |   0m  0s |  The patch does not contain any @author tags.  |
| -1 :x: |  test4tests  |   0m  0s |  The patch doesn't appear to include any new or modified tests. Please justify why no new tests are needed for this patch. Also please list what manual steps were performed to verify this patch.  |
||| _ 4.x Compile Tests _ |
| +1 :green_heart: |  mvninstall  |  11m 33s |  4.x passed  |
| +1 :green_heart: |  compile  |   0m 55s |  4.x passed  |
| +1 :green_heart: |  checkstyle  |   0m 40s |  4.x passed  |
| +1 :green_heart: |  javadoc  |   0m 45s |  4.x passed  |
| +0 :ok: |  spotbugs  |   2m 57s |  phoenix-core in 4.x has 951 extant spotbugs warnings.  |
||| _ Patch Compile Tests _ |
| +1 :green_heart: |  mvninstall  |   5m 27s |  the patch passed  |
| +1 :green_heart: |  compile  |   0m 54s |  the patch passed  |
| +1 :green_heart: |  javac  |   0m 54s |  the patch passed  |
| -1 :x: |  checkstyle  |   0m 40s |  phoenix-core: The patch generated 2 new + 430 unchanged - 2 fixed = 432 total (was 432)  |
| +1 :green_heart: |  whitespace  |   0m  0s |  The patch has no whitespace issues.  |
| +1 :green_heart: |  javadoc  |   0m 47s |  the patch passed  |
| +1 :green_heart: |  spotbugs  |   3m  7s |  the patch passed  |
||| _ Other Tests _ |
| -1 :x: |  unit  | 136m 43s |  phoenix-core in the patch failed.  |
| +1 :green_heart: |  asflicense  |   0m 35s |  The patch does not generate ASF License warnings.  |
|  |   | 168m 22s |   |


| Reason | Tests |
|-------:|:------|
| Failed junit tests | phoenix.end2end.index.GlobalImmutableTxIndexIT |
|   | phoenix.end2end.InListIT |
|   | phoenix.end2end.MetaDataEndpointImplIT |


| Subsystem | Report/Notes |
|----------:|:-------------|
| Docker | ClientAPI=1.41 ServerAPI=1.41 base: https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1012/5/artifact/yetus-general-check/output/Dockerfile |
| GITHUB PR | https://github.com/apache/phoenix/pull/1012 |
| JIRA Issue | PHOENIX-6256 |
| Optional Tests | dupname asflicense javac javadoc unit spotbugs hbaseanti checkstyle compile |
| uname | Linux 822b172343bd 4.15.0-112-generic #113-Ubuntu SMP Thu Jul 9 23:41:39 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux |
| Build tool | maven |
| Personality | dev/phoenix-personality.sh |
| git revision | 4.x / 4b272b1 |
| Default Java | Private Build-1.8.0_242-8u242-b08-0ubuntu3~16.04-b08 |
| checkstyle | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1012/5/artifact/yetus-general-check/output/diff-checkstyle-phoenix-core.txt |
| unit | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1012/5/artifact/yetus-general-check/output/patch-unit-phoenix-core.txt |
|  Test Results | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1012/5/testReport/ |
| Max. process+thread count | 6683 (vs. ulimit of 30000) |
| modules | C: phoenix-core U: phoenix-core |
| Console output | https://ci-hadoop.apache.org/job/Phoenix/job/Phoenix-PreCommit-GitHub-PR/job/PR-1012/5/console |
| versions | git=2.7.4 maven=3.3.9 spotbugs=4.1.3 |
| Powered by | Apache Yetus 0.12.0 https://yetus.apache.org |


This message was automatically generated.

**Comment by ChinmaySKulkarni** [comment]
Test failures are unrelated. Committing.

**Pull request merged**
