### PR TITLE
Fix for performance.py not using JAVA_HOME

### PR DESCRIPTION
**Pull request by bpanneton**

### CODE REVIEW

**Comment by chu11** [comment]
Note: This patch is for https://issues.apache.org/jira/browse/PHOENIX-2303

My only comment is should this patch look at hbase-env (similar to queryserver.py)?

**Comment by bpanneton** [comment]
Yea, that would be better. I'll fix it up.

**Comment by bpanneton** [comment]
Patch should now follow how queryserver.py gets the JAVA_HOME dir

**Comment by chu11** [comment]
There's another call to 'java' later on in the performance.py that also needs to be adjusted.

**Comment by bpanneton** [comment]
Fixed the java that I missed.

**Comment by chu11** [comment]
LGTM

**Comment by bpanneton** [comment]
Updated to have sqlline, sqlline-thing and psql in there.

**Comment by stoty** [comment]
Already merged as PHOENIX-2303

**Pull request closed without merging**
