### PR TITLE
PHOENIX-6692 Add HBase 2.5 support

### PR DESCRIPTION
**Pull request by stoty**

### CODE REVIEW

**Comment by stoty** [comment]
The errors are because I have also updated the default HBase 2.4 version

**Comment by virajjasani** [comment]
Shall we backport [this commit](https://github.com/apache/phoenix/commit/c389aef32be427fd2d0ff0bef114f01e6256a507) as well? Otherwise looks good overall.

**Comment by stoty** [comment]
No, in this branch we still support 2.1 and 2.2, which use an older zookeeper where the JARs are not split, @virajjasani.
I checked that we're adding the zk-jute dependency in the 2.5 profile here.

**Review by virajjasani — APPROVED** [review]

**Comment by stoty** [comment]
I just realized that we've removed a lot stuff from the compatibility module in 5.2, which is missing here.

**Comment by stoty** [comment]
Running the suite with the Hbase 2.5 profile, I get:

> [ERROR] Failures: 
> [ERROR]   WALRecoveryRegionPostOpenIT.testRecoveryRegionPostOpen:245
> [ERROR]   ViewTTLIT.testDeleteWithOnlyTenantView:1969->upsertDataAndRunValidations:2331->validateExpiredRowsAreNotReturnedUsingData:2392->verifyRowsBeforeTTLExpiration:2453 Rows upserted and fetched do not match, upserted=5, fetched=4 expected:<[00B0y0000000001, 00B0y0000000002, 00B0y0000000003, 00B0y0000000004, 00B0y0000000005]> but was:<[00B0y0000000001, 00B0y0000000002, 00B0y0000000003, 00B0y0000000004]>
> [ERROR] Errors: 
> [ERROR]   AlterTableWithViewsIT.testCreateViewWithPropsMaintainsOwnProps:309 NullPointer
> [ERROR]   AlterTableWithViewsIT.testCreateViewWithPropsMaintainsOwnProps:309 NullPointer
> [ERROR]   AlterTableWithViewsIT.testCreateViewWithPropsMaintainsOwnProps:309 NullPointer
> [ERROR]   AlterTableWithViewsIT.testCreateViewWithPropsMaintainsOwnProps:309 NullPointer

There is also a logging problem with the phoenix-pherf tests, but that's a trivial fix.

**Comment by stoty** [comment]
I get the same WALRecoveryRegionPostOpenIT error on master on the same test machine.

**Comment by stoty** [comment]
ViewTTLIT is simply flakey, see PHOENIX-6843 .

**Comment by stoty** [comment]
AlterTableWithViewsIT failed because Tephra does not support Hbase 2.5.
I have disabled Tephra for Hbase 2.5+

**Comment by stoty** [comment]
The first version was very unfinished.
The current version runs the full test suite without errors with -Dhbase.profile=2.5

Can you please take a look again @virajjasani ?

**Comment by virajjasani** [comment]
Ah yes I see, also the latest IT failure (PermissionNSEnabled*) is known flaky.
Went through the changes again and looks good to go. Thanks @stoty

**Comment by virajjasani** [comment]
> I just realized that we've removed a lot stuff from the compatibility module in 5.2, which is missing here.

Yeah I realized now the same.

**Review by virajjasani — APPROVED** [review]

**Pull request closed without merging**
